(function(b){b.anvsoftJavaScriptSlideshowTemplate=b.aJSsTemplate=b.aJSsTemplate||{version:"1.0.0",global:b}})(window);(function(){aJSsTemplate.ExternalInterface=function(b){this.globalPath=b.globalPath;this.container=b.container;this.commandDispatcher=b.commandDispatcher;this.copyright=b.copyright;this.movieWidth=b.movieWidth;this.movieHeight=b.movieHeight;this.startAutoPlay=b.startAutoPlay;this.continuum=b.continuum;this.clickToAutoPlay=b.clickToAutoPlay;this.randomPlayingPhotos=b.randomPlayingPhotos;this.enableURL=b.enableURL;this.movieBackgroundColor=b.movieBackgroundColor;this.loadStyle=b.loadStyle;this.anvsoftMenu=
b.anvsoftMenu;this.frameRate=b.frameRate;var a=b.globalTitleXml;this.showTitle=a.getAttribute("showTitle");this.photoTitleColor=a.getAttribute("photoTitleColor").replace(/0x/g,"#");this.photoTitleBackgroundColor=a.getAttribute("backgroundColor").replace(/0x/g,"#");this.photoTitleAlpha=a.getAttribute("alpha")/100;this.photoTitleAutoHide=a.getAttribute("autoHide");this.titleTextFont=a.getAttribute("titleTextFont");this.titleTextSize=a.getAttribute("titleTextSize");this.titleTextAlign=a.getAttribute("titleTextAlign");
this.titleTextShadowColor=a.getAttribute("titleTextShadowColor").replace(/0x/g,"#");this.titleTextShadowOffset=Number(a.getAttribute("titleTextShadowOffset"));this.titleTextShadowBlur=Number(a.getAttribute("titleTextShadowBlur"));this.textResize=a.getAttribute("textResize");this.textTransform=Number(a.getAttribute("textTransform"));this.textTransformOriginX=Number(a.getAttribute("textTransformOriginX"));this.textTransformOriginY=Number(a.getAttribute("textTransformOriginY"));this.titleTransform=Number(a.getAttribute("titleTransform"));
this.titleTransformOriginX=Number(a.getAttribute("titleTransformOriginX"));this.titleTransformOriginY=Number(a.getAttribute("titleTransformOriginY"));this.musicPath=b.musicPath;this.musicStream=b.musicStream;this.musicLoop=b.musicLoop;this.musicAutoPlay=b.musicAutoPlay;this.topPadding=b.topPadding;this.bottomPadding=b.bottomPadding;this.leftPadding=b.leftPadding;this.rightPadding=b.rightPadding;var c=b.globalDescriptionXml;this.enableDes=c.getAttribute("enable");this.desTextFont=c.getAttribute("defaultTextFont");
this.desTextSize=c.getAttribute("defaultTextSize");this.desTextColor=c.getAttribute("defaultTextColor").replace(/0x/g,"#");this.desLineHeight=Number(c.getAttribute("lineHeight"));this.desTextAlign=c.getAttribute("desTextAlign");this.desTextShadowColor=c.getAttribute("desTextShadowColor").replace(/0x/g,"#");this.desTextShadowOffset=Number(c.getAttribute("desTextShadowOffset"));this.desTextShadowBlur=Number(c.getAttribute("desTextShadowBlur"));this.desTransform=Number(a.getAttribute("desTransform"));
this.desTransformOriginX=Number(a.getAttribute("desTransformOriginX"));this.desTransformOriginY=Number(a.getAttribute("desTransformOriginY"));this.videoAutoPlay=b.videoAutoPlay;this.bufferTime=b.bufferTime;this.videoControls=b.videoControls;a=b.thumbnailBasicXml;this.thumWidth=Number(a.getAttribute("thumWidth"));this.thumHeight=Number(a.getAttribute("thumHeight"));this.thumborder=Number(a.getAttribute("thumborder"));this.thumSpacing=Number(a.getAttribute("thumSpacing"));this.thumbnailBorderColor=
a.getAttribute("borderColor").replace(/0x/g,"#");this.currentBorderColor=a.getAttribute("currentBorderColor").replace(/0x/g,"#");this.currenThumBoxShadow=a.getAttribute("currenThumBoxShadow").replace(/0x/g,"#");this.thumBox=Number(a.getAttribute("thumBox"));this.thumBodyAlpha=a.getAttribute("thumBodyAlpha")/100;this.thumBoxColor=a.getAttribute("thumBoxColor").replace(/0x/g,"#");this.thumbnailArray=b.thumbnailArray;this.photoArray=b.photoArray;this.photoUrlArray=b.photoUrlArray;this.URLTarget=b.URLTarget;
this.videoArray=b.videoArray;this.transitionArray=b.transitionArray;this.photoTimeArray=b.photoTimeArray;this.transitionTimeArray=b.transitionTimeArray;this.defineTransitionArray=b.defineTransitionArray;this.photoTitleArray=b.photoTitleArray;this.descriptionText=b.descriptionText;this.photoCount=this.photoArray.length;this.Play=function(){b.Play()};this.Pause=function(){b.Pause()};this.Previous=function(){b.Previous()};this.Next=function(){b.Next()};this.Show=function(a,c){b.Show(a,c)};this.MusicPlay=
function(){b.MusicPlay()};this.MusicPause=function(){b.MusicPause()}}})();(function(){aJSsTemplate.ColorConverter={hexToRGB:function(b){var a,c,d;if(/rgb/.test(b))b=b.match(/\d+/g),a=parseInt(b[0]),c=parseInt(b[1]),d=parseInt(b[2]);else if(/#/.test(b)){var f=b.length;7===f?(a=parseInt(b.slice(1,3),16),c=parseInt(b.slice(3,5),16),d=parseInt(b.slice(5),16)):4===f&&(a=parseInt(b.charAt(1)+b.charAt(1),16),c=parseInt(b.charAt(2)+b.charAt(2),16),d=parseInt(b.charAt(3)+b.charAt(3),16))}else return b;return{r:a,g:c,b:d}}}})();(function(){aJSsTemplate.JsBackground=function(){}})();(function(){aJSsTemplate.JsText=function(b,a){function c(a){a=a.index;""!=n[a]?(v.style.display="true"!==p?"block":"none",v.textContent=n[a]):v.style.display="none"}function d(){"true"==p&&(v.style.display="none",H.style.cursor="pointer",a.addEventListener("mouseover",e),a.addEventListener("mouseout",h))}function f(a){a=a.index;""!=J[a]?(D.style.display="block",D.innerHTML=J[a]):D.style.display="none"}function e(){v.style.display="block"}function h(){v.style.display="none"}var j=b.movieWidth,i=b.topPadding,
g=b.leftPadding,l=b.rightPadding,m=b.showTitle,p=b.photoTitleAutoHide,n=b.photoTitleArray,q=b.photoTitleAlpha,k=b.photoTitleColor,r=b.titleTextAlign,t=b.titleTextFont,x=b.titleTextSize,A=b.titleTextShadowColor,y=b.titleTextShadowOffset,U=b.titleTextShadowBlur,w=b.textResize,E=b.textTransform,F=b.textTransformOriginX,M=b.textTransformOriginY,N=b.titleTransform,R=b.titleTransformOriginX,C=b.titleTransformOriginY,G=aJSsTemplate.ColorConverter.hexToRGB(b.photoTitleBackgroundColor),O=b.enableDes,u=b.desLineHeight,
J=b.descriptionText,z=b.desTextFont,s=b.desTextSize,I=b.desTextColor,P=b.desTextAlign,L=b.desTextShadowColor,T=b.desTextShadowOffset,K=b.desTextShadowBlur,B=b.desTransform,W=b.desTransformOriginX,S=b.desTransformOriginY,H=document.createElement("div");a.appendChild(H);H.style.position="absolute";H.style.top=i+"px";H.style.display="block";H.style.width=j-g-l+"px";H.style.backgroundColor="rgba("+G.r+","+G.g+","+G.b+","+q+")";H.style.backgroundRepeat="repeat";H.style.webkitTransform="rotate("+E+"deg)";
H.style.msTransform="rotate("+E+"deg)";H.style.MozTransform="rotate("+E+"deg)";H.style.OTransform="rotate("+E+"deg)";H.style.transform="rotate("+E+"deg)";H.style.transformOrigin=""+M+"px "+F+"px";H.style.webkitTransformOrigin=""+M+"px "+F+"px";H.style.MozTransformOrigin=""+M+"px "+F+"px";H.style.OTransformOrigin=""+M+"px "+F+"px";H.style.resize=""+w+"";H.style.overflow="auto";if("true"==m){var v=document.createElement("div");H.appendChild(v);v.textContent=n[0];v.style.webkitTransform="rotate("+N+
"deg)";v.style.msTransform="rotate("+N+"deg)";v.style.MozTransform="rotate("+N+"deg)";v.style.OTransform="rotate("+N+"deg)";v.style.transform="rotate("+N+"deg)";v.style.transformOrigin=""+C+"px "+R+"px";v.style.webkitTransformOrigin=""+C+"px "+R+"px";v.style.MozTransformOrigin=""+C+"px "+R+"px";v.style.OTransformOrigin=""+C+"px "+R+"px";v.style.color=k;v.style.textAlign=r;v.style.fontFamily=t;v.style.fontSize=x+"px";v.style.textTransform="none";v.style.padding="12px 12px 12px 12px";v.style.fontWeight=
"bold";v.style.textShadow=y+"px "+y+"px "+U+"px "+A;b.commandDispatcher.addEventListener("photoLoadComplete",c);b.commandDispatcher.addEventListener("photoLoadComplete",d)}if("true"==O){var D=document.createElement("div");H.appendChild(D);D.innerHTML=J[0];D.style.webkitTransform="rotate("+B+"deg)";D.style.msTransform="rotate("+B+"deg)";D.style.MozTransform="rotate("+B+"deg)";D.style.OTransform="rotate("+B+"deg)";D.style.transform="rotate("+B+"deg)";D.style.transformOrigin=""+S+"px "+W+"px";D.style.webkitTransformOrigin=
""+S+"px "+W+"px";D.style.MozTransformOrigin=""+S+"px "+W+"px";D.style.OTransformOrigin=""+S+"px "+W+"px";D.style.textAlign=P;D.style.fontSize=s+"px";D.style.color=I;D.style.padding="12px 12px 12px 12px";D.style.fontFamily=z;D.style.lineHeight=u+"px";D.style.textTransform="none";D.style.textShadow=T+"px "+T+"px "+K+"px "+L;b.commandDispatcher.addEventListener("photoLoadComplete",f)}}})();(function(){aJSsTemplate.JsThumbnail=function(b,a){function c(){L.scrollLeft-=N}function d(){L.scrollLeft+=N}globalPath=b.globalPath;a.style.overflow="hidden";var f=Number(b.movieWidth),e=Number(b.movieHeight),h=Number(b.bottomPadding),j=Number(b.leftPadding),i=Number(b.rightPadding),g=b.startAutoPlay,l=b.continuum,m=b.clickToAutoPlay,p=b.musicPath,n=b.musicAutoPlay,q=b.photoArray,k=b.thumbnailArray,r=b.thumWidth,t=b.thumHeight,x=b.thumbnailBorderColor,A=b.currentBorderColor,y=b.thumborder,U=b.thumSpacing,
w=0,E=aJSsTemplate.ColorConverter.hexToRGB(b.thumBoxColor),F=b.thumBodyAlpha,M=t+2*y+35,N=f-40,R=0,C=0,G=parseInt((N+U)/(r+2*y+U)),O=C=0,u=document.createElement("div");a.appendChild(u);u.id="thumBody";u.style.position="absolute";u.style.top=e-M+"px";u.style.left=j+"px";u.style.width=f-j-i+"px";u.style.height=M+"px";u.style.margin="0px auto";u.style.backgroundColor="rgba("+E.r+","+E.g+","+E.b+","+F+")";var J=document.createElement("div");a.appendChild(J);J.style.position="absolute";J.style.top=e-
M-20+"px";J.style.left=(f-j-i)/2-50+"px";J.style.width="100px";J.style.height="20px";J.style.backgroundColor="rgba("+E.r+","+E.g+","+E.b+","+F+")";J.innerHTML="\ufe3d";J.style.textAlign="center";J.style.fontSize="20px";J.style.color="#ff0000";J.style.fontFamily="Lucida Sans Unicode";J.style.fontWeight="bold";var z=document.createElement("div");u.appendChild(z);z.style.position="absolute";z.style.backgroundImage="url("+globalPath+"../res/play.png)";z.style.backgroundPosition="0 0%";z.style.top="3px";
z.style.left="7px";z.style.width="16px";z.style.height="10px";z.style.display="block";z.style.cursor="pointer";C=document.createElement("div");u.appendChild(C);C.style.position="absolute";C.style.left="30px";C.style.width="1px";C.style.height="15px";C.style.backgroundColor="#ffffff";var s=document.createElement("div");u.appendChild(s);s.style.position="absolute";s.innerHTML="play music";s.style.top="-3px";s.style.left="40px";s.style.width="80px";s.style.height="14px";s.style.display="block";s.style.cursor=
"pointer";s.style.fontSize="13px";s.style.color="#ffffff";s.style.fontFamily="Lucida Sans Unicode";s.style.fontWeight="bold";var I=document.createElement("div");u.appendChild(I);I.style.position="absolute";I.style.display="block";I.style.background="url("+globalPath+"../res/prev.png)";I.style.top="3px";I.style.left=f-50+10+"px";I.style.width="9px";I.style.height="10px";I.style.cursor="pointer";var P=document.createElement("div");u.appendChild(P);P.style.position="absolute";P.style.display="block";P.style.top=
"3px";P.style.left=f-10-10+"px";P.style.background="url("+globalPath+"../res/next.png)";P.style.width="11px";P.style.height="10px";P.style.cursor="pointer";C=document.createElement("div");u.appendChild(C);C.style.position="absolute";C.style.left=f-50+"px";C.style.width="1px";C.style.height="15px";C.style.backgroundColor="#ffffff";E=document.createElement("div");u.appendChild(E);E.style.position="absolute";E.style.background="url("+globalPath+"../res/prev.png)";E.style.top=M-(t+2*y+10)-5+(t+2*y+10)/2-4.5+
"px";E.style.left="5px";E.style.width="9px";E.style.height="10px";F=document.createElement("div");u.appendChild(F);F.style.position="absolute";F.style.left=N+24+"px";F.style.background="url("+globalPath+"../res/next.png)";F.style.top=M-(t+2*y+10)-5+(t+2*y+10)/2-4.5+"px";F.style.left=f-j-11-5+"px";F.style.width="11px";F.style.height="10px";var L=document.createElement("div");u.appendChild(L);L.id="showThumbnails";L.style.position="absolute";L.style.top=M-(t+2*y+10)-5+"px";L.style.left="20px";L.style.width=
N+"px";L.style.height=t+2*y+10+"px";L.style.overflow="hidden";var T=document.createElement("div");L.appendChild(T);T.id="showArea";if(b.photoCount>G){for(var C=(N-G*(r+2*y)-6)/(G-1),K=0;K<b.photoCount;K++){var B=new Image;B.style.width=r+"px";B.style.height=t+"px";B.style.cssFloat="left";B.style.display="block";B.style.cursor="pointer";B.style.borderWidth=y+"px";B.style.borderStyle="solid";B.style.borderColor=x;1==(K+1)%G&&(B.style.marginLeft="3px");B.style.marginRight=0==(K+1)%G?"3px":C+"px";B.style.marginTop=
"5px";B.src=globalPath+k[K];B.alt=q[K];B.index=K;R=N*Math.ceil(b.photoCount/G);T.appendChild(B)}B.style.marginRight="0px";T.style.width=R+"px";T.style.height=t+2*y+10+"px";var W=R}E.style.cursor="pointer";F.style.cursor="pointer";E.onclick=function(){0==L.scrollLeft?L.scrollLeft=W:setTimeout(c,0)};F.onclick=function(){L.scrollLeft+N==W?L.scrollLeft=0:setTimeout(d,0)};if(b.photoCount<=G){for(K=0;K<b.photoCount;K++)B=new Image,B.style.marginTop="5px",B.style.width=r+"px",B.style.height=t+"px",B.style.display=
"block",B.style.cssFloat="left",B.style.cursor="pointer",B.style.borderWidth=y+"px",B.style.borderStyle="solid",B.style.borderColor=x,1==(K+1)%G&&(B.style.marginLeft="3px"),0==(K+1)%G&&(B.style.marginRight="3px"),B.style.marginRight=U+"px",B.src=globalPath+k[K],B.alt=q[K],B.index=K,R+=N,T.appendChild(B);B.style.marginRight="0px";T.style.width=R+"px";T.style.height=t+2*y+10+"px"}I.onclick=function(){"true"==g?"true"==m?0<w?(b.Show(w-1,1),z.style.backgroundPosition="0 100%",v=0):(b.Show(b.photoCount-
1,1),z.style.backgroundPosition="0 100%",w=v=0):0<w?(b.Show(w-1,0),z.style.backgroundPosition="0 0%",v=1):(b.Show(b.photoCount-1,0),z.style.backgroundPosition="0 0%",v=1,w=0):"true"==m?0<w?(b.Show(w-1,1),z.style.backgroundPosition="0 100%",v=1):(b.Show(b.photoCount-1,1),z.style.backgroundPosition="0 100%",v=1,w=0):0<w?(b.Show(w-1,0),z.style.backgroundPosition="0 0%",v=0):(b.Show(b.photoCount-1,0),z.style.backgroundPosition="0 0%",w=v=0)};P.onclick=function(){"true"==g?"true"==m?w<b.photoCount-1?(b.Show(w+
1,1),z.style.backgroundPosition="0 100%",v=0):(b.Show(0,1),z.style.backgroundPosition="0 100%",w=v=0):w<b.photoCount-1?(b.Show(w+1,0),z.style.backgroundPosition="0 0%",v=1):(b.Show(0,0),z.style.backgroundPosition="0 0%",v=1,w=0):"true"==m?w<b.photoCount-1?(b.Show(w+1,1),z.style.backgroundPosition="0 100%",v=1):(b.Show(0,1),z.style.backgroundPosition="0 100%",v=1,w=0):w<b.photoCount-1?(b.Show(w+1,0),z.style.backgroundPosition="0 0%",v=0):(b.Show(0,0),z.style.backgroundPosition="0 0%",w=v=0)};for(var S=
T.getElementsByTagName("img"),K=0;K<b.photoCount;K++)S[K].onmouseover=function(){w!==this.index?(this.style.borderColor=x,this.style.boxShadow="0 0 0px 1px "+x+""):(this.style.borderColor=A,this.style.boxShadow="0 0 0px 1px "+A+"")},S[K].onclick=function(){for(var a=0;a<b.photoCount;a++)S[a].style.borderColor=x;S[this.index].style.borderColor=A;w=this.index;"true"==g?"true"==m?(b.Show(w,1),z.style.backgroundPosition="0 100%",v=0):(b.Show(w,0),z.style.backgroundPosition="0 0%",v=1):"true"==m?(b.Show(w,
1),z.style.backgroundPosition="0 100%",v=1):(b.Show(w,0),z.style.backgroundPosition="0 0%",v=0)},S[K].onmouseout=function(){this.style.boxShadow=w!==this.index?"0 0 0 0 "+x+"":"0 0 0 0 "+A+""};b.commandDispatcher.addEventListener("photoLoadComplete",function(a){for(var c=0;c<b.photoCount;c++)S[c].style.borderColor=x,S[c].style.boxShadow="0 0 0 0 "+x+"";S[a.index].style.borderColor=A;S[a.index].style.boxShadow="0 0 0 0 "+A+"";w=a.index;w>=b.photoCount-1&&("false"==l&&"false"==b.randomPlayingPhotos)&&
(z.style.backgroundPosition="0 0%",b.Pause(),v=0);O=parseInt(w/G);L.scrollLeft=N*O});J.style.cursor="pointer";var H=0;J.innerHTML="\ufe3e";J.onclick=function(){0==H?(J.innerHTML="\ufe3d",setTimeout(function(){Y=setInterval(Z,10)},1),H=1):(J.innerHTML="\ufe3e",V>e-h-M&&setTimeout(function(){$=setInterval(aa,10)},1),H=0)};z.style.cursor="pointer";z.onmouseover=function(){};z.onmouseout=function(){};var v=0;"true"==g?(z.style.backgroundPosition="0 100%",z.onclick=function(){0==v?(z.style.backgroundPosition=
"0 0",b.Pause(),v=1):(z.style.backgroundPosition="0 100%",b.Play(),v=0)}):(z.style.backgroundPosition="0 0",z.onclick=function(){0==v?(z.style.backgroundPosition="0 100%",b.Play(),v=1):(z.style.backgroundPosition="0 0",b.Pause(),v=0)});s.onmouseover=function(){};s.onmouseout=function(){};var D=0;""==p?s.style.display="none":"true"==n?(s.innerHTML="play music",s.onclick=function(){0==D?(s.innerHTML="stop music",b.MusicPause(),D=1):(s.innerHTML="play music",b.MusicPlay(),D=0)}):(s.innerHTML="stop music",
s.onclick=function(){0==D?(s.innerHTML="play music",b.MusicPlay(),D=1):(s.innerHTML="stop music",b.MusicPause(),D=0)});b.commandDispatcher.addEventListener("soundPlayComplete",function(){s.innerHTML="stop music";D=1});b.commandDispatcher.addEventListener("videoPlayEnded",function(){z.style.display="none";I.style.left="10px";P.style.left=j+(f-j-i)/2+"px"});var V=e-M,X=e-M-20,Y,Z=function(){V+=5;X+=5;u.style.top=V+"px";J.style.top=X+"px";V>=e-h&&(clearInterval(Y),u.style.visibility="hidden",J.style.top=
e-h-20+"px")},$,aa=function(){u.style.visibility="";V-=5;X-=5;u.style.top=V+"px";J.style.top=X+"px";V<=e-h-M&&(clearInterval($),u.style.top=e-30-M-2)},p=navigator.userAgent,p=p.toLowerCase();switch((/(webkit)[ \/]([\w.]+)/.exec(p)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(p)||/(msie) ([\w.]+)/.exec(p)||!/compatible/.test(p)&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(p)||[])[1]){case "webkit":a.style.height="100%"}}})();(function(){aJSsTemplate.JsMenu=function(b,a){var c=b.movieWidth,d=b.movieHeight,f=b.bottomPadding,e=b.rightPadding,h=b.copyright;if(null==b.anvsoftMenu||"anvsoftPFMTheme"!=h&&"anvsoftUSSTheme"!=h&&"anvsoftHSMTheme"!=h){var j;switch(h){case "anvsoftPFMTheme":j="Photo Slideshow Maker";break;case "anvsoftUSSTheme":j="Ultra Slideshow";break;case "anvsoftHSMTheme":j="guyueshuiming";break;case "anvsoftSWWTheme":j="SlideWow";break;default:j="Anvsoft Photo Slideshow"}var i=document.createElement("div");
i.style.position="absolute";i.style.cursor="pointer";i.style.padding="5px";i.style.backgroundColor="rgba(0, 0, 0, 0.8)";i.style.display="none";i.style.textShadow="1px 1px 1px #000";i.style.borderRadius="5px";i.style.color="#FFF";i.style.font="normal normal 10px/12px verdana,tahoma,arial,sans-serif";i.textContent=j;a.appendChild(i);i.style.left=c-e-i.scrollWidth-5+"px";i.style.top=d-f-i.scrollHeight-5+"px";i.onclick=function(){switch(h){case "anvsoftPFMTheme":window.open("http://www.photo-flash-maker.com/","_self");break;
case "anvsoftUSSTheme":window.open("http://www.ultraslideshow.com/","_self");break;case "anvsoftHSMTheme":window.open("http://www.html5-slideshow-maker.com/","_self");break;case "anvsoftSWWTheme":window.open("http://www.slidewow.com/","_self");break;default:window.open("http://www.anvsoft.com/","_self")}}}}})();(function(){aJSsTemplate.Main=function(b){var b=new aJSsTemplate.ExternalInterface(b),a=b.container;new aJSsTemplate.JsBackground(b,a);new aJSsTemplate.JsText(b,a);new aJSsTemplate.JsThumbnail(b,a);new aJSsTemplate.JsMenu(b,a)}})();(function(b){function a(a,c,b){for(var d=a.length,i=c.length,g,l,m,p,n,q,k=0,r=0;r<d;r++){g=a[r];l=a[r<d-1?r+1:0];k=g.y-l.y;g=l.x-g.x;l=Math.sqrt(k*k+g*g);k/=l;g/=l;l=m=a[0].x*k+a[0].y*g;for(var t=1;t<d;t++)q=a[t].x*k+a[t].y*g,q>m?m=q:q<l&&(l=q);p=n=c[0].x*k+c[0].y*g;for(t=1;t<i;t++)q=c[t].x*k+c[t].y*g,q>n?n=q:q<p&&(p=q);l<p?(l=p-m,k=-k,g=-g):l-=n;if(0<=l)return!1;l>b.overlap&&(b.overlap=l,b.normal.x=k,b.normal.y=g)}return b}var c=b.Quark=b.Quark||{version:"1.0.0",global:b},d=function(){};c.inherit=
function(a,c){d.prototype=c.prototype;a.superClass=c.prototype;a.prototype=new d;a.prototype.constructor=a};c.merge=function(a,c,b){for(var d in c)if(!b||a.hasOwnProperty(d)||void 0!==a[d])a[d]=c[d];return a};c.delegate=function(a,c){var d=c||b;if(2<arguments.length){var j=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.concat.apply(j,arguments);return a.apply(d,c)}}return function(){return a.apply(d,arguments)}};c.getDOM=function(a){return document.getElementById(a)};
c.createDOM=function(a,c){var b=document.createElement(a),d;for(d in c){var i=c[d];if("style"==d)for(var g in i)b.style[g]=i[g];else b[d]=i}return b};c.use=function(a){for(var a=a.split("."),c=b,d=0;d<a.length;d++)var j=a[d],c=c[j]||(c[j]={});return c};(function(a){var c=a.ua=navigator.userAgent;a.isWebKit=/webkit/i.test(c);a.isMozilla=/mozilla/i.test(c);a.isIE=/msie/i.test(c);a.isFirefox=/firefox/i.test(c);a.isChrome=/chrome/i.test(c);a.isSafari=/safari/i.test(c)&&!this.isChrome;a.isMobile=/mobile/i.test(c);
a.isOpera=/opera/i.test(c);a.isIOS=/ios/i.test(c);a.isIpad=/ipad/i.test(c);a.isIpod=/ipod/i.test(c);a.isIphone=/iphone/i.test(c)&&!this.isIpod;a.isAndroid=/android/i.test(c);a.supportStorage="localStorage"in b;a.supportOrientation="orientation"in b;a.supportDeviceMotion="ondevicemotion"in b;a.supportTouch="ontouchstart"in b;a.supportCanvas=null!=document.createElement("canvas").getContext;a.cssPrefix=a.isWebKit?"webkit":a.isFirefox?"Moz":a.isOpera?"O":a.isIE?"ms":""})(c);c.getElementOffset=function(a){for(var c=
a.offsetLeft,b=a.offsetTop;(a=a.offsetParent)&&a!=document.body&&a!=document;)c+=a.offsetLeft,b+=a.offsetTop;return{left:c,top:b}};c.createDOMDrawable=function(a,b){var d=a.tagName||"div",j=b.image,i=a.width||j&&j.width,g=a.height||j&&j.height,l=c.createDOM(d);a.id&&(l.id=a.id);l.style.position="absolute";l.style.left=(a.left||0)+"px";l.style.top=(a.top||0)+"px";l.style.width=i+"px";l.style.height=g+"px";if("canvas"==d)l.width=i,l.height=g,j&&(d=l.getContext("2d"),i=b.rect||[0,0,i,g],d.drawImage(j,
i[0],i[1],i[2],i[3],a.x||0,a.y||0,a.width||i[2],a.height||i[3]));else if(l.style.opacity=void 0!=a.alpha?a.alpha:1,l.style.overflow="hidden",j&&j.src)l.style.backgroundImage="url("+j.src+")",l.style.backgroundPosition=-(a.rectX||0)+"px "+-(a.rectY||0)+"px";return l};c.DEG_TO_RAD=Math.PI/180;c.RAD_TO_DEG=180/Math.PI;c.hitTestPoint=function(a,c,b,d){var a=a.getBounds(),i=a.length,g=c>=a.x&&c<=a.x+a.width&&b>=a.y&&b<=a.y+a.height;if(g&&d){for(var d=0,g=!1,l,m,p,n,q=0;q<i;q++){var k=a[q],r=a[(q+1)%i];
k.y==r.y&&b==k.y&&(k.x>r.x?(l=r.x,m=k.x):(l=k.x,m=r.x),c>=l&&c<=m)?g=!0:(k.y>r.y?(p=r.y,n=k.y):(p=k.y,n=r.y),b<p||b>n||(k=(b-k.y)*(r.x-k.x)/(r.y-k.y)+k.x,k>c?d++:k==c&&(g=!0)))}return g?0:1==d%2?1:-1}return g?1:-1};c.hitTestObject=function(a,b,d){a=a.getBounds();b=b.getBounds();return(a=a.x<=b.x+b.width&&b.x<=a.x+a.width&&a.y<=b.y+b.height&&b.y<=a.y+a.height)&&d?(a=c.polygonCollision(b,b),!1!==a):a};c.polygonCollision=function(c,b){var d=a(c,b,{overlap:-Infinity,normal:{x:0,y:0}});return d?a(b,c,
d):!1};c.toString=function(){return"Quark"};c.trace=function(){var a=Array.prototype.slice.call(arguments);"undefined"!=typeof console&&"undefined"!=typeof console.log&&console.log(a.join(" "))};void 0==b.Q&&(b.Q=c);void 0==b.trace&&(b.trace=c.trace)})(window);
(function(){var b=Quark.Matrix=function(a,c,b,f,e,h){this.a=a;this.b=c;this.c=b;this.d=f;this.tx=e;this.ty=h};b.prototype.concat=function(a){var c=this.a,b=this.c,f=this.tx;this.a=c*a.a+this.b*a.c;this.b=c*a.b+this.b*a.d;this.c=b*a.a+this.d*a.c;this.d=b*a.b+this.d*a.d;this.tx=f*a.a+this.ty*a.c+a.tx;this.ty=f*a.b+this.ty*a.d+a.ty;return this};b.prototype.rotate=function(a){var c=Math.cos(a),a=Math.sin(a),b=this.a,f=this.c,e=this.tx;this.a=b*c-this.b*a;this.b=b*a+this.b*c;this.c=f*c-this.d*a;this.d=
f*a+this.d*c;this.tx=e*c-this.ty*a;this.ty=e*a+this.ty*c;return this};b.prototype.scale=function(a,c){this.a*=a;this.d*=c;this.tx*=a;this.ty*=c;return this};b.prototype.translate=function(a,c){this.tx+=a;this.ty+=c;return this};b.prototype.identity=function(){this.a=this.d=1;this.b=this.c=this.tx=this.ty=0;return this};b.prototype.invert=function(){var a=this.a,c=this.b,b=this.c,f=this.d,e=this.tx,h=a*f-c*b;this.a=f/h;this.b=-c/h;this.c=-b/h;this.d=a/h;this.tx=(b*this.ty-f*e)/h;this.ty=-(a*this.ty-
c*e)/h;return this};b.prototype.transformPoint=function(a,c,b){var f=a.x*this.a+a.y*this.c+this.tx,e=a.x*this.b+a.y*this.d+this.ty;c&&(f=f+0.5>>0,e=e+0.5>>0);if(b)return{x:f,y:e};a.x=f;a.y=e;return a};b.prototype.clone=function(){return new b(this.a,this.b,this.c,this.d,this.tx,this.ty)};b.prototype.toString=function(){return"(a="+this.a+", b="+this.b+", c="+this.c+", d="+this.d+", tx="+this.tx+", ty="+this.ty+")"}})();
(function(){var b=Quark.Rectangle=function(a,c,b,f){this.x=a;this.y=c;this.width=b;this.height=f};b.prototype.intersects=function(a){return this.x<=a.x+a.width&&a.x<=this.x+this.width&&this.y<=a.y+a.height&&a.y<=this.y+this.height};b.prototype.intersection=function(a){var c=Math.max(this.x,a.x),d=Math.min(this.x+this.width,a.x+a.width);if(c<=d){var f=Math.max(this.y,a.y),a=Math.min(this.y+this.height,a.y+a.height);if(f<=a)return new b(c,f,d-c,a-f)}return null};b.prototype.union=function(a,c){var d=
Math.max(this.x+this.width,a.x+a.width),f=Math.max(this.y+this.height,a.y+a.height),e=Math.min(this.x,a.x),h=Math.min(this.y,a.y),d=d-e,f=f-h;if(c)return new b(e,h,d,f);this.x=e;this.y=h;this.width=d;this.height=f};b.prototype.containsPoint=function(a,c){return this.x<=a&&a<=this.x+this.width&&this.y<=c&&c<=this.y+this.height};b.prototype.clone=function(){return new b(this.x,this.y,this.width,this.height)};b.prototype.toString=function(){return"(x="+this.x+", y="+this.y+", width="+this.width+", height="+
this.height+")"}})();
(function(){Quark.KEY={MOUSE_LEFT:1,MOUSE_MID:2,MOUSE_RIGHT:3,BACKSPACE:8,TAB:9,NUM_CENTER:12,ENTER:13,RETURN:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,CAPS_LOCK:20,ESC:27,ESCAPE:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,PRINT_SCREEN:44,INSERT:45,DELETE:46,ZERO:48,ONE:49,TWO:50,THREE:51,FOUR:52,FIVE:53,SIX:54,SEVEN:55,EIGHT:56,NINE:57,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90,
CONTEXT_MENU:93,NUM_ZERO:96,NUM_ONE:97,NUM_TWO:98,NUM_THREE:99,NUM_FOUR:100,NUM_FIVE:101,NUM_SIX:102,NUM_SEVEN:103,NUM_EIGHT:104,NUM_NINE:105,NUM_MULTIPLY:106,NUM_PLUS:107,NUM_MINUS:109,NUM_PERIOD:110,NUM_DIVISION:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123}})();
(function(){var b=Quark.EventManager=function(){this.keyState={};this._evtHandlers={}};b.prototype.registerStage=function(a,c,b,f){this.register(a.context.canvas,c,{host:a,func:a._onEvent},b,f)};b.prototype.unregisterStage=function(a,c){this.unregister(a.context.canvas,c,a.onEvent)};b.prototype.register=function(a,c,b,f,e){if(null==b||"function"==typeof b)b={host:null,func:b};for(var h={prevent:f,stop:e},j=this,f=function(a){j._onEvent(a,h,b)},e=0;e<c.length;e++){for(var i=c[e],g=this._evtHandlers[i]||
(this._evtHandlers[i]=[]),l=0,m=!1;l<g.length;l++){var p=g[l];if(p.target==a&&p.callback.func==b.func){trace("duplicate callback");m=!0;break}}m||(g.push({target:a,callback:b,handler:f}),a.addEventListener(i,f,!1))}};b.prototype.unregister=function(a,c,b){for(var f=0;f<c.length;f++)for(var e=c[f],h=this._evtHandlers[e],j=0;j<h.length;j++){var i=h[j];if(i.target==a&&(i.callback.func==b||null==b)){a.removeEventListener(e,i.handler);h.splice(j,1);break}}};b.prototype._onEvent=function(a,c,d){var f=a,
e=a.type;0==a.type.indexOf("touch")&&(f=a.touches&&0<a.touches.length?a.touches[0]:a.changedTouches&&0<a.changedTouches.length?a.changedTouches[0]:a,f.type=e);if("keydown"==e||"keyup"==e||"keypress"==e)this.keyState[a.keyCode]=e;null!=d.func&&d.func.call(d.host,f);b.stop(a,!c.prevent,!c.stop)};b.stop=function(a,c,b){c||a.preventDefault();b||(a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation())}})();
(function(){var b=Quark.EventDispatcher=function(){this._eventMap={}};b.prototype.addEventListener=function(a,c){var b=this._eventMap[a];null==b&&(b=this._eventMap[a]=[]);return-1==b.indexOf(c)?(b.push(c),!0):!1};b.prototype.removeEventListener=function(a,c){var b=this._eventMap[a];if(null==b)return!1;for(var f=0;f<b.length;f++)if(b[f]===c)return b.splice(f,1),0==b.length&&delete this._eventMap[a],!0;return!1};b.prototype.removeEventListenerByType=function(a){return null!=this._eventMap[a]?(delete this._eventMap[a],
!0):!1};b.prototype.removeAllEventListeners=function(){this._eventMap={}};b.prototype.dispatchEvent=function(a){var c=this._eventMap[a.type];if(null==c)return!1;a.target||(a.target=this);for(var c=c.slice(),b=0;b<c.length;b++){var f=c[b];"function"==typeof f&&f.call(this,a)}return!0};b.prototype.hasEventListener=function(a){a=this._eventMap[a];return null!=a&&0<a.length};b.prototype.on=b.prototype.addEventListener;b.prototype.un=b.prototype.removeEventListener;b.prototype.fire=b.prototype.dispatchEvent})();
(function(){var b=Quark.UIDUtil={_counter:0};b.createUID=function(a){var c=a.charCodeAt(a.length-1);48<=c&&57>=c&&(a+="_");return a+this._counter++};b.displayObjectToString=function(a){for(var c;null!=a;a=a.parent){var b=null!=a.id?a.id:a.name;c=null==c?b:b+"."+c;if(a==a.parent)break}return c}})();
(function(){function b(a,c){for(var d=0;d<a.children.length;d++){var j=a.children[d];if(j.children)b(j,c);else if(null!=c){j=j.getBounds();c.globalAlpha=0.2;c.beginPath();var i=j[0];c.moveTo(i.x-0.5,i.y-0.5);for(var g=1;g<j.length;g++){var l=j[g];c.lineTo(l.x-0.5,l.y-0.5)}c.lineTo(i.x-0.5,i.y-0.5);c.stroke();c.closePath();c.globalAlpha=0.5;c.beginPath();c.rect((j.x>>0)-0.5,(j.y>>0)-0.5,j.width>>0,j.height>>0);c.stroke();c.closePath()}else j.drawable.domDrawable&&(j.drawable.domDrawable.style.border=
"1px solid #f00")}}Quark.getUrlParams=function(){var a,c={},b=window.location.href,d=b.indexOf("?");if(0<d){b=b.substring(d+1).split("&");for(d=0;a=b[d];d++)a=b[d]=a.split("="),c[a[0]]=1<a.length?a[1]:!0}return c};var a=document.getElementsByTagName("head")[0],c=a.getElementsByTagName("meta"),d=0<c.length?c[c.length-1].nextSibling:a.childNodes[0];Quark.addMeta=function(c){var b=document.createElement("meta"),h;for(h in c)b.setAttribute(h,c[h]);a.insertBefore(b,d)};Quark.toggleDebugRect=function(a){a.debug=
!a.debug;a._render=a.debug?function(c){null!=c.clear&&c.clear(0,0,a.width,a.height);Quark.Stage.superClass._render.call(a,c);c=a.context.context;null!=c&&(c.save(),c.lineWidth=1,c.strokeStyle="#f00",c.globalAlpha=0.5);b(a,c);null!=c&&c.restore()}:function(c){null!=c.clear&&c.clear(0,0,a.width,a.height);Quark.Stage.superClass._render.call(a,c)}}})();
(function(){var b=Quark.Timer=function(a){this.interval=a||50;this.paused=!1;this.info={lastTime:0,currentTime:0,deltaTime:0,realDeltaTime:0};this._startTime=0;this._intervalID=null;this._listeners=[]};b.prototype.start=function(){if(null==this._intervalID){this._startTime=this.info.lastTime=this.info.currentTime=Date.now();var a=this,c=function(){a._intervalID=setTimeout(c,a.interval);a._run()};c()}};b.prototype.stop=function(){clearTimeout(this._intervalID);this._intervalID=null;this._startTime=
0};b.prototype.pause=function(){this.paused=!0};b.prototype.resume=function(){this.paused=!1};b.prototype._run=function(){if(!this.paused){var a=this.info,c=a.currentTime=Date.now();a.deltaTime=a.realDeltaTime=c-a.lastTime;for(var b=0,f=this._listeners.length,e,h;b<f;b++)e=this._listeners[b],h=e.__runTime||0,0==h?e.step(this.info):c>h&&(e.step(this.info),this._listeners.splice(b,1),b--,f--);a.lastTime=c}};b.prototype.delay=function(a,c){this.addListener({step:a,__runTime:Date.now()+c})};b.prototype.addListener=
function(a){if(null==a||"function"!=typeof a.step)throw"Timer Error: The listener object must implement a step() method!";this._listeners.push(a)};b.prototype.removeListener=function(a){a=this._listeners.indexOf(a);-1<a&&this._listeners.splice(a,1)}})();
(function(){var b=Quark.ImageLoader=function(a){b.superClass.constructor.call(this);this.loading=!1;this._index=-1;this._loaded=0;this._images={};this._totalSize=0;this._loadHandler=Quark.delegate(this._loadHandler,this);this._addSource(a)};Quark.inherit(b,Quark.EventDispatcher);b.prototype.load=function(a){this._addSource(a);this.loading||this._loadNext()};b.prototype._addSource=function(a){if(a){for(var a=a instanceof Array?a:[a],c=0;c<a.length;c++)this._totalSize+=a[c].size||0;this._source=this._source?
this._source.concat(a):a}};b.prototype._loadNext=function(){this._index++;if(this._index>=this._source.length)this.dispatchEvent({type:"complete",target:this,images:this._images}),this._source=[],this.loading=!1,this._index=-1;else{var a=new Image;a.onload=this._loadHandler;a.src=this._source[this._index].src;this.loading=!0}};b.prototype._loadHandler=function(a){this._loaded++;var c=this._source[this._index];c.image=a.target;this._images[c.id||c.src]=c;this.dispatchEvent({type:"loaded",target:this,
image:c});this._loadNext()};b.prototype.getLoaded=function(){return this._loaded};b.prototype.getTotal=function(){return this._source.length};b.prototype.getLoadedSize=function(){var a=0,c;for(c in this._images)a+=this._images[c].size||0;return a};b.prototype.getTotalSize=function(){return this._totalSize}})();
(function(){var b=Quark.Tween=function(c,b,f){this.target=c;this.delay=this.time=0;this.reverse=this.loop=this.paused=!1;this.interval=0;this.ease=a.Linear.EaseNone;this.onComplete=this.onUpdate=this.onStart=this.next=null;this._oldProps={};this._newProps={};this._deltaProps={};this._pausedStartTime=this._pausedTime=this._lastTime=this._startTime=0;this._reverseFlag=1;this._frameCount=this._frameTotal=0;for(var e in b){var h=c[e],j=b[e];void 0!==h&&"number"==typeof h&&"number"==typeof j&&(this._oldProps[e]=
h,this._newProps[e]=j,this._deltaProps[e]=j-h)}for(e in f)this[e]=f[e]};b.prototype.setProps=function(a,b){for(var f in a)this.target[f]=this._oldProps[f]=a[f];for(f in b)this._newProps[f]=b[f],this._deltaProps[f]=b[f]-this.target[f]};b.prototype._init=function(){this._startTime=Date.now()+this.delay;this._pausedTime=0;0<this.interval&&(this._frameTotal=Math.round(this.time/this.interval));b.add(this)};b.prototype.start=function(){this._init();this.paused=!1};b.prototype.stop=function(){b.remove(this)};
b.prototype.pause=function(){this.paused=!0;this._pausedStartTime=Date.now()};b.prototype.resume=function(){this.paused=!1;this._pausedTime+=Date.now()-this._pausedStartTime};b.prototype._update=function(){if(!this.paused){var a=Date.now(),d=a-this._startTime-this._pausedTime;if(!(0>d)){if(0==this._lastTime&&null!=this.onStart)this.onStart(this);this._lastTime=a;a=0<this._frameTotal?++this._frameCount/this._frameTotal:d/this.time;1<a&&(a=1);var d=this.ease(a),f;for(f in this._oldProps)this.target[f]=
this._oldProps[f]+this._deltaProps[f]*this._reverseFlag*d;if(null!=this.onUpdate)this.onUpdate(this,d);if(1<=a){if(this.reverse){if(f=this._oldProps,this._oldProps=this._newProps,this._newProps=f,this._startTime=Date.now(),this._frameCount=0,this._reverseFlag*=-1,!this.loop)this.reverse=!1}else if(this.loop){for(f in this._oldProps)this.target[f]=this._oldProps[f];this._startTime=Date.now();this._frameCount=0}else if(b.remove(this),f=this.next,null!=f&&(f instanceof b?(a=f,f=null):a=f.shift(),null!=
a))a.next=f,a.start();if(null!=this.onComplete)this.onComplete(this)}}}};b._tweens=[];b.step=function(){for(var a=this._tweens,b=a.length;0<=--b;)a[b]._update()};b.add=function(a){-1==this._tweens.indexOf(a)&&this._tweens.push(a);return this};b.remove=function(a){var b=this._tweens,a=b.indexOf(a);-1<a&&b.splice(a,1);return this};b.to=function(a,d,f){a=new b(a,d,f);a._init();return a};b.from=function(a,d,f){d=new b(a,d,f);f=d._oldProps;d._oldProps=d._newProps;d._newProps=f;d._reverseFlag=-1;for(var e in d._oldProps)a[e]=
d._oldProps[e];d._init();return d};var a=Quark.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{}};a.Linear.EaseNone=function(a){return a};a.Quadratic.EaseIn=function(a){return a*a};a.Quadratic.EaseOut=function(a){return-a*(a-2)};a.Quadratic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a:-0.5*(--a*(a-2)-1)};a.Cubic.EaseIn=function(a){return a*a*a};a.Cubic.EaseOut=function(a){return--a*a*a+1};a.Cubic.EaseInOut=function(a){return 1>
(a*=2)?0.5*a*a*a:0.5*((a-=2)*a*a+2)};a.Quartic.EaseIn=function(a){return a*a*a*a};a.Quartic.EaseOut=function(a){return-(--a*a*a*a-1)};a.Quartic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*a*a:-0.5*((a-=2)*a*a*a-2)};a.Quintic.EaseIn=function(a){return a*a*a*a*a};a.Quintic.EaseOut=function(a){return(a-=1)*a*a*a*a+1};a.Quintic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*a*a*a:0.5*((a-=2)*a*a*a*a+2)};a.Sinusoidal.EaseIn=function(a){return-Math.cos(a*Math.PI/2)+1};a.Sinusoidal.EaseOut=function(a){return Math.sin(a*
Math.PI/2)};a.Sinusoidal.EaseInOut=function(a){return-0.5*(Math.cos(Math.PI*a)-1)};a.Exponential.EaseIn=function(a){return 0==a?0:Math.pow(2,10*(a-1))};a.Exponential.EaseOut=function(a){return 1==a?1:-Math.pow(2,-10*a)+1};a.Exponential.EaseInOut=function(a){return 0==a?0:1==a?1:1>(a*=2)?0.5*Math.pow(2,10*(a-1)):0.5*(-Math.pow(2,-10*(a-1))+2)};a.Circular.EaseIn=function(a){return-(Math.sqrt(1-a*a)-1)};a.Circular.EaseOut=function(a){return Math.sqrt(1- --a*a)};a.Circular.EaseInOut=function(a){return 1>
(a/=0.5)?-0.5*(Math.sqrt(1-a*a)-1):0.5*(Math.sqrt(1-(a-=2)*a)+1)};a.Elastic.EaseIn=function(a){var b,f=0.1,e=0.4;if(0==a)return 0;if(1==a)return 1;e||(e=0.3);!f||1>f?(f=1,b=e/4):b=e/(2*Math.PI)*Math.asin(1/f);return-(f*Math.pow(2,10*(a-=1))*Math.sin(2*(a-b)*Math.PI/e))};a.Elastic.EaseOut=function(a){var b,f=0.1,e=0.4;if(0==a)return 0;if(1==a)return 1;e||(e=0.3);!f||1>f?(f=1,b=e/4):b=e/(2*Math.PI)*Math.asin(1/f);return f*Math.pow(2,-10*a)*Math.sin(2*(a-b)*Math.PI/e)+1};a.Elastic.EaseInOut=function(a){var b,
f=0.1,e=0.4;if(0==a)return 0;if(1==a)return 1;e||(e=0.3);!f||1>f?(f=1,b=e/4):b=e/(2*Math.PI)*Math.asin(1/f);return 1>(a*=2)?-0.5*f*Math.pow(2,10*(a-=1))*Math.sin(2*(a-b)*Math.PI/e):0.5*f*Math.pow(2,-10*(a-=1))*Math.sin(2*(a-b)*Math.PI/e)+1};a.Back.EaseIn=function(a){return a*a*(2.70158*a-1.70158)};a.Back.EaseOut=function(a){return(a-=1)*a*(2.70158*a+1.70158)+1};a.Back.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*(3.5949095*a-2.5949095):0.5*((a-=2)*a*(3.5949095*a+2.5949095)+2)};a.Bounce.EaseIn=function(b){return 1-
a.Bounce.EaseOut(1-b)};a.Bounce.EaseOut=function(a){return(a/=1)<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375};a.Bounce.EaseInOut=function(b){return 0.5>b?0.5*a.Bounce.EaseIn(2*b):0.5*a.Bounce.EaseOut(2*b-1)+0.5}})();
(function(){var b=Quark.Audio=function(a,c,d,f){b.superClass.constructor.call(this);this.src=a;this.autoPlay=c&&d;this.loop=f;this._playing=this._loaded=!1;this._evtHandler=Quark.delegate(this._evtHandler,this);this._element=document.createElement("audio");this._element.preload=c;a=a.substr(0,a.lastIndexOf("."));d=document.createElement("source");this._element.canPlayType("audio/mpeg")?(d.type="audio/mpeg",d.src=a+".mp3"):(d.type="audio/ogg",d.src=a+".ogg");this._element.appendChild(d);c&&this.load()};
Quark.inherit(b,Quark.EventDispatcher);b.prototype.load=function(){this._element.addEventListener("progress",this._evtHandler,!1);this._element.addEventListener("ended",this._evtHandler,!1);this._element.addEventListener("error",this._evtHandler,!1);try{this._element.load()}catch(a){trace(a)}this.progressCheck=setTimeout(function(){b._element.removeEventListener("progress",b._evtHandler);b._element.removeEventListener("error",b._evtHandler);b._loaded=!0;b.dispatchEvent({type:"loaded",target:b});b.autoPlay&&
b.play();clearTimeout(b.progressCheck);b=b.progressCheck=null},1E3);var b=this};b.prototype._evtHandler=function(a){clearTimeout(this.progressCheck);if("progress"==a.type){var b=0,d=0,f=a.target.buffered;if(f&&0<f.length)for(b=f.length-1;0<=b;b--)d=f.end(b)-f.start(b);if(1<=d/a.target.duration||isNaN(a.target.duration))this._element.removeEventListener("progress",this._evtHandler),this._element.removeEventListener("error",this._evtHandler),this._loaded=!0,this.dispatchEvent({type:"loaded",target:this}),
this.autoPlay&&this.play()}else"ended"==a.type?(this.dispatchEvent({type:"ended",target:this}),this.loop?this.play():this._playing=!1):"error"==a.type&&trace("Quark.Audio Error: "+a.target.src)};b.prototype.play=function(){this._loaded?(this._element.play(),this._playing=!0):(this.autoPlay=!0,this.load())};b.prototype.stop=function(){this._playing&&(this._element.pause(),this._playing=!1)};b.prototype.loaded=function(){return this._loaded};b.prototype.playing=function(){return this._playing}})();
(function(){var b=Quark.Drawable=function(a,b){this.domDrawable=this.rawDrawable=null;this.set(a,b)};b.prototype.get=function(a,b){if(null==b||null!=b.canvas.getContext)return this.rawDrawable;null==this.domDrawable&&(this.domDrawable=Quark.createDOMDrawable(a,{image:this.rawDrawable}));return this.domDrawable};b.prototype.set=function(a,b){if(null==a?0:a instanceof HTMLImageElement||a instanceof HTMLCanvasElement||a instanceof HTMLVideoElement)this.rawDrawable=a;!0===b?this.domDrawable=a:this.domDrawable&&
(this.domDrawable.style.backgroundImage="url("+this.rawDrawable.src+")")}})();
(function(){var b=Quark.DisplayObject=function(a){this.id=Quark.UIDUtil.createUID("DisplayObject");this.name=null;this.height=this.width=this.regY=this.regX=this.y=this.x=0;this.scaleY=this.scaleX=this.alpha=1;this.rotation=0;this.transformEnabled=this.eventEnabled=this.visible=!0;this.useHandCursor=!1;this.context=this.parent=this.drawable=this.polyArea=null;this._depth=0;this._lastState={};this._stateList="x y regX regY width height alpha scaleX scaleY rotation visible _depth".split(" ");Quark.merge(this,
a,!0);a.mixin&&Quark.merge(this,a.mixin,!1)};b.prototype.setDrawable=function(a){null==this.drawable?this.drawable=new Quark.Drawable(a):this.drawable.rawDrawable!=a&&this.drawable.set(a)};b.prototype.getDrawable=function(a){return this.drawable&&this.drawable.get(this,a)};b.prototype._update=function(a){this.update(a)};b.prototype.update=function(){};b.prototype._render=function(a){a=this.context||a;!this.visible||0>=this.alpha?(null!=a.hide&&a.hide(this),this.saveState(["visible","alpha"])):(a.startDraw(),
a.transform(this),this.render(a),a.endDraw(),this.saveState())};b.prototype.render=function(a){a.draw(this,0,0,this.width,this.height,0,0,this.width,this.height)};b.prototype._onEvent=function(a){if(null!=this.onEvent)this.onEvent(a)};b.prototype.onEvent=null;b.prototype.saveState=function(a){for(var a=a||this._stateList,b=this._lastState,d=0,f=a.length;d<f;d++){var e=a[d];b["last"+e]=this[e]}};b.prototype.getState=function(a){return this._lastState["last"+a]};b.prototype.propChanged=function(){for(var a=
0<arguments.length?arguments:this._stateList,b=0,d=a.length;b<d;b++){var f=a[b];if(this._lastState["last"+f]!=this[f])return!0}return!1};b.prototype.hitTestPoint=function(a,b,d){return Quark.hitTestPoint(this,a,b,d)};b.prototype.hitTestObject=function(a,b){return Quark.hitTestObject(this,a,b)};b.prototype.localToGlobal=function(a,b){var d=this.getConcatenatedMatrix();return{x:d.tx+a,y:d.ty+b}};b.prototype.globalToLocal=function(a,b){var d=this.getConcatenatedMatrix().invert();return{x:d.tx+a,y:d.ty+
b}};b.prototype.localToTarget=function(a,b,d){a=this.localToGlobal(a,b);return d.globalToLocal(a.x,a.y)};b.prototype.getConcatenatedMatrix=function(a){var b=new Quark.Matrix(1,0,0,1,0,0);if(a==this)return b;for(var d=this;null!=d.parent&&d.parent!=a;d=d.parent){var f=1,e=0;0!=d.rotation%360&&(e=d.rotation*Quark.DEG_TO_RAD,f=Math.cos(e),e=Math.sin(e));0!=d.regX&&(b.tx-=d.regX);0!=d.regY&&(b.ty-=d.regY);b.concat(new Quark.Matrix(f*d.scaleX,e*d.scaleX,-e*d.scaleY,f*d.scaleY,d.x,d.y))}return b};b.prototype.getBounds=
function(){var a=this.width,b=this.height,d=this.getConcatenatedMatrix(),a=this.polyArea||[{x:0,y:0},{x:a,y:0},{x:a,y:b},{x:0,y:b}],b=[],f=a.length,e,h,j,i,g;e=d.transformPoint(a[0],!0,!0);h=j=e.x;i=g=e.y;b[0]=e;for(var l=1;l<f;l++)e=d.transformPoint(a[l],!0,!0),h>e.x?h=e.x:j<e.x&&(j=e.x),i>e.y?i=e.y:g<e.y&&(g=e.y),b[l]=e;b.x=h;b.y=i;b.width=j-h;b.height=g-i;return b};b.prototype.getCurrentWidth=function(){return Math.abs(this.width*this.scaleX)};b.prototype.getCurrentHeight=function(){return Math.abs(this.height*
this.scaleY)};b.prototype.getStage=function(){for(var a=this;a.parent;)a=a.parent;return a instanceof Quark.Stage?a:null};b.prototype.toString=function(){return Quark.UIDUtil.displayObjectToString(this)}})();
(function(){var b=Quark.DisplayObjectContainer=function(a){this.eventChildren=!0;this.autoSize=!1;this.children=[];a=a||{};b.superClass.constructor.call(this,a);this.id=a.id||Quark.UIDUtil.createUID("DisplayObjectContainer");this.setDrawable(a.drawable||a.image||null);if(a.children)for(var c=0;c<a.children.length;c++)this.addChild(a.children[c])};Quark.inherit(b,Quark.DisplayObject);b.prototype.addChildAt=function(a,b){0>b?b=0:b>this.children.length&&(b=this.children.length);var d=this.getChildIndex(a);
if(-1!=d){if(d==b)return this;this.children.splice(d,1)}else a.parent&&a.parent.removeChild(a);this.children.splice(b,0,a);a.parent=this;if(this.autoSize){var d=new Quark.Rectangle(0,0,this.rectWidth||this.width,this.rectHeight||this.height),f=new Quark.Rectangle(a.x,a.y,a.rectWidth||a.width,a.rectHeight||a.height);d.union(f);this.width=d.width;this.height=d.height}return this};b.prototype.addChild=function(a){for(var b=this.children.length,d=0;d<arguments.length;d++)a=arguments[d],this.addChildAt(a,
b+d);return this};b.prototype.removeChildAt=function(a){if(0>a||a>=this.children.length)return!1;var b=this.children[a];null!=b&&(this.getStage().context.remove(b),b.parent=null);this.children.splice(a,1);return!0};b.prototype.removeChild=function(a){return this.removeChildAt(this.children.indexOf(a))};b.prototype.removeAllChildren=function(){for(;0<this.children.length;)this.removeChildAt(0)};b.prototype.getChildAt=function(a){return 0>a||a>=this.children.length?null:this.children[a]};b.prototype.getChildIndex=
function(a){return this.children.indexOf(a)};b.prototype.setChildIndex=function(a,b){if(a.parent==this){var d=this.children.indexOf(a);b!=d&&(this.children.splice(d,1),this.children.splice(b,0,a))}};b.prototype.swapChildren=function(a,b){var d=this.getChildIndex(a),f=this.getChildIndex(b);this.children[d]=b;this.children[f]=a};b.prototype.swapChildrenAt=function(a,b){var d=this.getChildAt(a),f=this.getChildAt(b);this.children[a]=f;this.children[b]=d};b.prototype.getChildById=function(a){for(var b=
0,d=this.children.length;b<d;b++){var f=this.children[b];if(f.id==a)return f}return null};b.prototype.removeChildById=function(a){for(var b=0,d=this.children.length;b<d;b++)if(this.children[b].id==a)return this.removeChildAt(b);return null};b.prototype.sortChildren=function(a){var b=a;"string"==typeof b&&(b=function(a,f){return f[b]-a[b]});this.children.sort(b)};b.prototype.contains=function(a){return-1!=this.getChildIndex(a)};b.prototype.getNumChildren=function(){return this.children.length};b.prototype._update=
function(a){null!=this.update&&this.update(a);for(var b=this.children.slice(0),d=0,f=b.length;d<f;d++){var e=b[d];e._depth=d+1;e._update(a)}};b.prototype.render=function(a){b.superClass.render.call(this,a);for(var c=0,d=this.children.length;c<d;c++)this.children[c]._render(a)};b.prototype.getObjectUnderPoint=function(a,b,d,f){if(f)var e=[];for(var h=this.children.length-1;0<=h;h--){var j=this.children[h];if(!(null==j||!j.eventEnabled&&void 0==j.children||!j.visible||0>=j.alpha))if(void 0!=j.children&&
j.eventChildren&&0<j.getNumChildren()){var i=j.getObjectUnderPoint(a,b,d,f);if(i)if(f)0<i.length&&(e=e.concat(i));else return i;else if(0<=j.hitTestPoint(a,b,d))if(f)e.push(j);else return j}else if(0<=j.hitTestPoint(a,b,d))if(f)e.push(j);else return j}return f?e:null}})();
(function(){var b=Quark.Stage=function(a){this.stageY=this.stageX=0;this.paused=!1;this._eventTarget=null;a=a||{};b.superClass.constructor.call(this,a);this.id=a.id||Quark.UIDUtil.createUID("Stage");if(null==this.context)throw"Quark.Stage Error: context is required.";this.updatePosition()};Quark.inherit(b,Quark.DisplayObjectContainer);b.prototype.step=function(a){this.paused||(this._update(a),this._render(this.context))};b.prototype._update=function(a){for(var b=this.children.slice(0),d=0,f=b.length;d<
f;d++){var e=b[d];e._depth=d+1;e._update(a)}null!=this.update&&this.update(a)};b.prototype._render=function(a){null!=a.clear&&a.clear(0,0,this.width,this.height);b.superClass._render.call(this,a)};b.prototype._onEvent=function(a){var b=a.pageX||a.clientX,d=a.pageY||a.clientY,b=(b-this.stageX)/this.scaleX,d=(d-this.stageY)/this.scaleY,f=this.getObjectUnderPoint(b,d,!0),e=this._eventTarget;a.eventX=b;a.eventY=d;null!=e&&e!=f&&(a.lastEventTarget=e,(b="mousemove"==a.type?"mouseout":"touchmove"==a.type?
"touchout":null)&&e._onEvent({type:b}),this._eventTarget=null);null!=f&&f.eventEnabled&&(a.eventTarget=e=this._eventTarget=f,f._onEvent(a));Quark.supportTouch||(this.context.canvas.style.cursor=e&&e.useHandCursor&&e.eventEnabled?"pointer":"");if(null!=this.onEvent)this.onEvent(a)};b.prototype.updatePosition=function(){var a=Quark.getElementOffset(this.context.canvas);this.stageX=a.left;this.stageY=a.top}})();
(function(){var b=Quark.Bitmap=function(a){this.image=null;this.rectHeight=this.rectWidth=this.rectY=this.rectX=0;a=a||{};b.superClass.constructor.call(this,a);this.id=a.id||Quark.UIDUtil.createUID("Bitmap");this.setRect(a.rect||[0,0,this.image.width,this.image.height]);this.setDrawable(this.image);this._stateList.push("rectX","rectY","rectWidth","rectHeight")};Quark.inherit(b,Quark.DisplayObject);b.prototype.setRect=function(a){this.rectX=a[0];this.rectY=a[1];this.rectWidth=this.width=a[2];this.rectHeight=
this.height=a[3]};b.prototype.render=function(a){a.draw(this,this.rectX,this.rectY,this.rectWidth,this.rectHeight,0,0,this.width,this.height)}})();
(function(){var b=Quark.MovieClip=function(a){this.interval=0;this.useFrames=this.paused=!1;this.currentFrame=0;this._frames=[];this._frameLabels={};this._frameDisObj=null;this._displayedCount=0;a=a||{};b.superClass.constructor.call(this,a);this.id=a.id||Quark.UIDUtil.createUID("MovieClip");a.frames&&this.addFrame(a.frames)};Quark.inherit(b,Quark.Bitmap);b.prototype.addFrame=function(a){var b=this._frames.length;if(a instanceof Array)for(var d=0;d<a.length;d++)this.setFrame(a[d],b+d);else this.setFrame(a,
b);return this};b.prototype.setFrame=function(a,b){void 0==b||b>this._frames.length?b=this._frames.length:0>b&&(b=0);this._frames[b]=a;a.label&&(this._frameLabels[a.label]=a);void 0==a.interval&&(a.interval=this.interval);0==b&&0==this.currentFrame&&this.setRect(a.rect)};b.prototype.getFrame=function(a){return"number"==typeof a?this._frames[a]:this._frameLabels[a]};b.prototype.play=function(){this.paused=!1};b.prototype.stop=function(){this.paused=!0};b.prototype.gotoAndStop=function(a){this.currentFrame=
this.getFrameIndex(a);this.paused=!0};b.prototype.gotoAndPlay=function(a){this.currentFrame=this.getFrameIndex(a);this.paused=!1};b.prototype.getFrameIndex=function(a){if("number"==typeof a)return a;for(var a=this._frameLabels[a],b=this._frames,d=0;d<b.length;d++)if(a==b[d])return d;return-1};b.prototype.nextFrame=function(a){var b=this._frames[this.currentFrame];0<b.interval&&(a=this._displayedCount+a,this._displayedCount=b.interval>a?a:0);if(0<=b.jump||"string"==typeof b.jump)if(0==this._displayedCount||
!b.interval)return this.currentFrame=this.getFrameIndex(b.jump);return 0<b.interval&&0<this._displayedCount?this.currentFrame:this.currentFrame>=this._frames.length-1?this.currentFrame=0:++this.currentFrame};b.prototype._update=function(a){var c=this._frames[this.currentFrame];c.stop?this.stop():(this.paused||this.nextFrame(this.useFrames?1:a&&a.deltaTime),this.setRect(c.rect),b.superClass._update.call(this,a))};b.prototype.render=function(a){var b=this._frames[this.currentFrame].rect;a.draw(this,
b[0],b[1],b[2],b[3],0,0,this.width,this.height)}})();
(function(){var b=Quark.Button=function(a){this.state=b.UP;this.enabled=!0;a=a||{};b.superClass.constructor.call(this,a);this.id=a.id||Quark.UIDUtil.createUID("Button");this._skin=new Quark.MovieClip({id:"skin",image:a.image});this.addChild(this._skin);this._skin.stop();this.eventChildren=!1;void 0===a.useHandCursor&&(this.useHandCursor=!0);a.up&&this.setUpState(a.up);a.over&&this.setOverState(a.over);a.down&&this.setDownState(a.down);a.disabled&&this.setDisabledState(a.disabled)};Quark.inherit(b,
Quark.DisplayObjectContainer);b.UP="up";b.OVER="over";b.DOWN="down";b.DISABLED="disabled";b.prototype.setUpState=function(a){a.label=b.UP;this._skin.setFrame(a,0);this.upState=a;return this};b.prototype.setOverState=function(a){a.label=b.OVER;this._skin.setFrame(a,1);this.overState=a;return this};b.prototype.setDownState=function(a){a.label=b.DOWN;this._skin.setFrame(a,2);this.downState=a;return this};b.prototype.setDisabledState=function(a){a.label=b.DISABLED;this._skin.setFrame(a,3);this.disabledState=
a;return this};b.prototype.setEnabled=function(a){if(this.enabled==a)return this;(this.eventEnabled=this.enabled=a)?3==this.currentFrame&&this._skin.gotoAndStop(b.UP):this.disabledState?this._skin.gotoAndStop(b.DISABLED):this._skin.gotoAndStop(b.state.UP);return this};b.prototype.changeState=function(a){if(this.state!=a){this.state=a;switch(a){case b.OVER:case b.DOWN:case b.UP:this.enabled||(this.eventEnabled=this.enabled=!0);this._skin.gotoAndStop(a);break;case b.DISABLED:this.setEnabled(!1)}return this}};
b.prototype._onEvent=function(a){if(this.enabled){switch(a.type){case "mousemove":this.overState&&this.changeState(b.OVER);break;case "mousedown":case "touchstart":case "touchmove":this.downState&&this.changeState(b.DOWN);break;case "mouseup":this.overState?this.changeState(b.OVER):this.changeState(b.UP);break;case "mouseout":case "touchout":case "touchend":this.upState&&this.changeState(b.UP)}b.superClass._onEvent.call(this,a)}};b.prototype.setDrawable=function(){b.superClass.setDrawable.call(this,
null)}})();
(function(){var b=Quark.Graphics=function(a){a=a||{};b.superClass.constructor.call(this,a);this.id=Quark.UIDUtil.createUID("Graphics");this.lineWidth=1;this.strokeStyle="0";this.lineAlpha=1;this.lineJoin=this.lineCap=null;this.miterLimit=10;this.fillStyle="0";this.fillAlpha=1;this._actions=[];this._cache=null};Quark.inherit(b,Quark.DisplayObject);b.prototype.lineStyle=function(a,b,d,f,e,h){this._addAction(["lineWidth",this.lineWidth=a||1]);this._addAction(["strokeStyle",this.strokeStyle=b||"0"]);
this._addAction(["lineAlpha",this.lineAlpha=d||1]);void 0!=f&&this._addAction(["lineCap",this.lineCap=f]);void 0!=e&&this._addAction(["lineJoin",this.lineJoin=e]);void 0!=h&&this._addAction(["miterLimit",this.miterLimit=h]);return this};b.prototype.beginFill=function(a,b){this._addAction(["fillStyle",this.fillStyle=a]);this._addAction(["fillAlpha",this.fillAlpha=b||1]);return this};b.prototype.endFill=function(){this._addAction(["stroke"]);this._addAction(["fill"]);return this};b.prototype.beginLinearGradientFill=
function(a,c,d,f,e,h){a=b._getContext().createLinearGradient(a,c,d,f);c=0;for(d=e.length;c<d;c++)a.addColorStop(h[c],e[c]);return this._addAction(["fillStyle",this.fillStyle=a])};b.prototype.beginRadialGradientFill=function(a,c,d,f,e,h,j,i){a=b._getContext().createRadialGradient(a,c,d,f,e,h);c=0;for(d=j.length;c<d;c++)a.addColorStop(i[c],j[c]);return this._addAction(["fillStyle",this.fillStyle=a])};b.prototype.beginBitmapFill=function(a,c){return this._addAction(["fillStyle",this.fillStyle=b._getContext().createPattern(a,
c||"")])};b.prototype.beginPath=function(){return this._addAction(["beginPath"])};b.prototype.closePath=function(){return this._addAction(["closePath"])};b.prototype.drawRect=function(a,b,d,f){return this._addAction(["rect",a,b,d,f])};b.prototype.drawRoundRectComplex=function(a,b,d,f,e,h,j,i){this._addAction(["moveTo",a+e,b]);this._addAction(["lineTo",a+d-h,b]);this._addAction(["arc",a+d-h,b+h,h,-Math.PI/2,0,!1]);this._addAction(["lineTo",a+d,b+f-j]);this._addAction(["arc",a+d-j,b+f-j,j,0,Math.PI/
2,!1]);this._addAction(["lineTo",a+i,b+f]);this._addAction(["arc",a+i,b+f-i,i,Math.PI/2,Math.PI,!1]);this._addAction(["lineTo",a,b+e]);this._addAction(["arc",a+e,b+e,e,Math.PI,3*Math.PI/2,!1]);return this};b.prototype.drawRoundRect=function(a,b,d,f,e){return this.drawRoundRectComplex(a,b,d,f,e,e,e,e)};b.prototype.drawCircle=function(a,b,d){return this._addAction(["arc",a+d,b+d,d,0,2*Math.PI,0])};b.prototype.drawEllipse=function(a,b,d,f){if(d==f)return this.drawCircle(a,b,d);var d=d/2,f=f/2,e=0.5522847498307933*
d,h=0.5522847498307933*f,a=a+d,b=b+f;this._addAction(["moveTo",a+d,b]);this._addAction(["bezierCurveTo",a+d,b-h,a+e,b-f,a,b-f]);this._addAction(["bezierCurveTo",a-e,b-f,a-d,b-h,a-d,b]);this._addAction(["bezierCurveTo",a-d,b+h,a-e,b+f,a,b+f]);this._addAction(["bezierCurveTo",a+e,b+f,a+d,b+h,a+d,b]);return this};b.prototype.render=function(a){var c=a.context;null==c?b.superClass.render.call(this,a):null!=this._cache?c.drawImage(this._cache,0,0):this._draw(c)};b.prototype._draw=function(a){for(var b=
0,d=this._actions.length;b<d;b++){var f=this._actions[b],e=f[0],h=1<f.length?f.slice(1):null;"function"==typeof a[e]?a[e].apply(a,h):a[e]=f[1]}};b.prototype.getDrawable=function(a){null==this.drawable&&this.setDrawable(this.toImage());return this.drawable.get(this,a)};b.prototype.cache=function(a){var b=Quark.createDOM("canvas",{width:this.width,height:this.height});this._draw(b.getContext("2d"));this._cache=b;a&&(this._cache=this.toImage());return this._cache};b.prototype.uncache=function(){this._cache=
null};b.prototype.toImage=function(a){var b=this._cache||this.cache(!0);if(b instanceof HTMLImageElement)return b;var d=new Image;d.src=b.toDataURL(a||"image/png");d.width=this.width;d.height=this.height;return d};b.prototype.clear=function(){this._cache=this._actions.length=0;this.lineWidth=1;this.strokeStyle="0";this.lineAlpha=1;this.lineJoin=this.lineCap=null;this.miterLimit=10;this.fillStyle="0";this.fillAlpha=1};b.prototype._addAction=function(a){this._actions.push(a);return this};b._getContext=
function(){var a=Quark.createDOM("canvas").getContext("2d");this._getContext=function(){return a};return a}})();(function(){var b=Quark.Context=function(a){if(null==a.canvas)throw"Quark.Context Error: canvas is required.";this.canvas=null;Quark.merge(this,a)};b.prototype.startDraw=function(){};b.prototype.draw=function(){};b.prototype.endDraw=function(){};b.prototype.transform=function(){};b.prototype.remove=function(){}})();
(function(){var b=Quark.CanvasContext=function(a){b.superClass.constructor.call(this,a);this.context=this.canvas.getContext("2d")};Quark.inherit(b,Quark.Context);b.prototype.startDraw=function(){this.context.save()};b.prototype.draw=function(a){var b=a.getDrawable(this);null!=b&&(arguments[0]=b,this.context.drawImage.apply(this.context,arguments))};b.prototype.endDraw=function(){this.context.restore()};b.prototype.transform=function(a){var b=this.context;a instanceof Q.Stage?(a._scaleX!=a.scaleX&&
(a._scaleX=a.scaleX,this.canvas.style.width=a._scaleX*a.width+"px"),a._scaleY!=a.scaleY&&(a._scaleY=a.scaleY,this.canvas.style.height=a._scaleY*a.height+"px")):((0!=a.x||0!=a.y)&&b.translate(a.x,a.y),0!=a.rotation%360&&b.rotate(a.rotation%360*Quark.DEG_TO_RAD),(1!=a.scaleX||1!=a.scaleY)&&b.scale(a.scaleX,a.scaleY),(0!=a.regX||0!=a.regY)&&b.translate(-a.regX,-a.regY));0<a.alpha&&(b.globalAlpha*=a.alpha)};b.prototype.clear=function(a,b,d,f){this.context.clearRect(a,b,d,f)}})();
(function(){function b(a,b){return b?""+("translate3d("+(a.x-a.regX)+"px, "+(a.y-a.regY)+"px, 0px)rotate3d(0, 0, 1, "+a.rotation+"deg)scale3d("+a.scaleX+", "+a.scaleY+", 1)"):""+("translate("+(a.x-a.regX)+"px, "+(a.y-a.regY)+"px)rotate("+a.rotation+"deg)scale("+a.scaleX+", "+a.scaleY+")")}var a=document.createElement("div"),c=void 0!=a.style[Quark.cssPrefix+"Transform"],d=void 0!=a.style[Quark.cssPrefix+"Perspective"],f=document.documentElement;if(d&&"webkitPerspective"in f.style){a.id="test3d";var e=
document.createElement("style");e.textContent="@media (-webkit-transform-3d){#test3d{height:3px}}";document.head.appendChild(e);f.appendChild(a);d=3===a.offsetHeight;e.parentNode.removeChild(e);a.parentNode.removeChild(a)}Quark.supportTransform=c;Quark.supportTransform3D=d;if(c){var h=Quark.DOMContext=function(a){h.superClass.constructor.call(this,a)};Quark.inherit(h,Quark.Context);h.prototype.draw=function(a){if(!a._addedToDOM){var b=a.parent,d=a.getDrawable(this);null==b&&null==d.parentNode?this.canvas.appendChild(d):
(b=b.getDrawable(this),d.parentNode!=b&&b.appendChild(d));a._addedToDOM=!0}};h.prototype.transform=function(a){var d=a.getDrawable(this);if(a.transformEnabled||!a._addedToDOM){var c=Quark.cssPrefix,e=c+"TransformOrigin",c=c+"Transform",d=d.style;if(!d.display||a.propChanged("visible","alpha"))d.display=!a.visible||0>=a.alpha?"none":"";if(!d.opacity||a.propChanged("alpha"))d.opacity=a.alpha;if(!d.backgroundPosition||a.propChanged("rectX","rectY"))d.backgroundPosition=-a.rectX+"px "+-a.rectY+"px";if(!d.width||
a.propChanged("width","height"))d.width=a.width+"px",d.height=a.height+"px";if(!d[e]||a.propChanged("regX","regY"))d[e]=a.regX+"px "+a.regY+"px";if(!d[c]||a.propChanged("x","y","regX","regY","scaleX","scaleY","rotation"))e=Quark.supportTransform3D?b(a,!0):b(a,!1),d[c]=e;if(!d.zIndex||a.propChanged("_depth"))d.zIndex=a._depth}};h.prototype.hide=function(a){a.getDrawable(this).style.display="none"};h.prototype.remove=function(a){var b=a.getDrawable(this),d=b.parentNode;null!=d&&d.removeChild(b);a._addedToDOM=
!1}}else trace("Warn: DOMContext requires css transfrom support.")})();(function(b){b.anvsoftJavaScriptSlideshow=b.aJSs=b.aJSs||{version:"1.0.0",global:b}})(window);
(function(){aJSs.Events={TRANSITION_OVER:"transitionOver",PLAY_CURRENT:"playCurrent",SOUND_PLAY_COMPLETE:"soundPlayComplete",PHOTO_MOUSE_OVER:"photoMouseOver",PHOTO_MOUSE_OUT:"photoMouseOut",PHOTO_LOAD_COMPLETE:"photoLoadComplete",PLAY_VIDEO:"playVideo",VIDEO_PLAY_ENDED:"videoPlayEnded",VIDEO_CLEAR:"videoClear",VIDEO_START_PLAY:"videoStartPlay",PLAY_NEXT:"playNext"}})();
(function(){var b=aJSs,a=function(){this.handlers={}};a.prototype={constructor:a,addEventListener:function(a,b){if(void 0!=a)"undefined"==typeof this.handlers[a]&&(this.handlers[a]=[]),this.handlers[a].push(b);else throw Error("undefined property events.");},dispatchEvent:function(a){a.target||(a.target=this);if(this.handlers[a.type]instanceof Array)for(var b=this.handlers[a.type],c=0,h=b.length;c<h;c++)b[c](a)},removeEventListener:function(a,b){if(this.handlers[a]instanceof Array){for(var c=this.handlers[a],
h=0,j=c.length;h<j&&c[h]!==b;h++);c.splice(h,1)}}};var c=new a;b.CommandDispatcher={getInstance:function(){return c}}})();(function(){aJSs.getParameters={parameters:function(){var b=document.getElementsByTagName("script");try{for(var a=b[b.length-1].src.split("?")[1].split("&"),b={},c,d,f,e=0,h=a.length;e<h;e++)c=a[e].split("="),d=c[0],f=c[1],"undefined"==typeof b[d]?b[d]=f:("string"==typeof b[d]&&(b[d]=[b[d]]),b[d].push(f));return b}catch(j){return[]}}}})();
(function(){aJSs.Music=function(b,a,c,d){var f="true"==d?!0:!1;this.soundAudio=new Quark.Audio(b,"true"==a?!0:!1,"true"==c?!0:!1,f);this.soundAudio.addEventListener("ended",function(){f||aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.SOUND_PLAY_COMPLETE})},!1);this.Playing=function(){return this.soundAudio.playing()};this.Play=function(){this.soundAudio.play()};this.Pause=function(){this.soundAudio.stop()}}})();
(function(){aJSs.Video=function(b,a,c,d,f,e){var a="true"==a?!0:!1,d="true"==d?!0:!1,b=b.substr(0,b.lastIndexOf(".")),h=document.createElement("video");h.width=f;h.height=e;try{h.buffered=c}catch(j){}h.autoplay=a;h.controls=d;h.loop=!1;h.preload="none";c=document.createElement("source");h.appendChild(c);h.canPlayType&&(""!=h.canPlayType("video/mp4")?(c.type="video/mp4",c.src=b+".mp4"):""!=h.canPlayType("video/ogg")?(c.type="video/ogg",c.src=b+".ogg"):""!=h.canPlayType("video/webm")?(c.type="video/webm",
c.src=b+".webm"):alert("Your browser does not support the video tag."));a?h.play():h.pause();h.addEventListener("ended",function(){aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.VIDEO_PLAY_ENDED})},!1);h.addEventListener("playing",function(){aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.VIDEO_START_PLAY})},!1);return h}})();
(function(){aJSs.MaskEffect=function(b){this.transTotal=68;this.maskerFull=0;var a=this,c,d;this.transition=function(a,b,d,c,i){this.maskerFull=0;if(a<=this.transTotal)this["mask"+a](b,d,c,i);else this.transition(68,b,d,c,i)};this.mask1=function(f,e,h,j){function i(){p=e*k*d;n=h*k*d;g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),g.setRect([0,0,e,h]),clearInterval(q),q=null}var g=f.getChildAt(0),l=0,m=0,p=0,n=
0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask2=function(f,e,h,j){function i(){p=e*k*d;g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),clearInterval(q),q=null}var g=f.getChildAt(0),l=0,m=0,p=0,n=h;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask3=function(f,e,h,j){function i(){n=h*k*d;g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),
g.setRect([0,0,e,h]),clearInterval(q),q=null}var g=f.getChildAt(0),l=0,m=0,p=e,n=0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask4=function(f,e,h,j){function i(){l=e*(1-k*d);p=e*k*d;g.x=e*(1-k*d);g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.x=0,clearInterval(q),q=null}var g=f.getChildAt(0),l=e,m=0,p=0,n=h;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask5=function(f,e,h,j){function i(){m=
h*(1-k*d);n=h*k*d;g.y=h*(1-k*d);g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.y=0,clearInterval(q),q=null}var g=f.getChildAt(0),l=0,m=h,p=e,n=0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask6=function(f,e,h,j){function i(){n=e*y*d;g.setRect([m,p,n,q]);k=e*(1-y*d);t=e*y*d;l.x=e*(1-y*d);l.setRect([k,r,t,x]);y++;if(y>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),
g.setRect([0,0,e,h]),f.removeChild(l),clearInterval(A),A=null}var g=f.getChildAt(0),l=new Quark.Bitmap({id:"targetBitmap2",image:g.image,rect:[0,0,0,0]});f.addChild(l);var m=0,p=0,n=0,q=h,k=e,r=0,t=0,x=h;c=j*b;d=1/(2*c);var A=setInterval(i,1E3/b),y=1;i()};this.mask7=function(f,e,h,j){function i(){q=h*y*d;g.setRect([m,p,n,q]);r=h*(1-y*d);x=h*y*d;l.y=h*(1-y*d);l.setRect([k,r,t,x]);y++;if(y>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,
e,h]),f.removeChild(l),clearInterval(A),A=null}var g=f.getChildAt(0),l=new Quark.Bitmap({id:"targetBitmap2",image:g.image,rect:[0,0,0,0]});f.addChild(l);var m=0,p=0,n=e,q=0,k=0,r=h,t=e,x=0;c=j*b;d=1/(2*c);var A=setInterval(i,1E3/b),y=1;i()};this.mask8=function(f,e,h,j){function i(){l=e/2*(1-k*d);p=e*k*d;g.x=e/2*(1-k*d);g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.x=0,clearInterval(q),q=null}var g=
f.getChildAt(0),l=e/2,m=0,p=0,n=h;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask9=function(f,e,h,j){function i(){m=h/2*(1-k*d);n=h*k*d;g.y=h/2*(1-k*d);g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.y=0,clearInterval(q),q=null}var g=f.getChildAt(0),l=0,m=h/2,p=e,n=0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask10=function(f,e,h,j){function i(){for(var b=0;b<m;b++){var j=b*p,i=
p*r*d,l=h;f.getChildById("maskBitmap"+b).setRect([j,0,i,l])}r++;if(r>c||1==a.maskerFull){aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"});for(g.setRect([0,0,e,h]);1<f.getNumChildren();)f.removeChildAt(f.getNumChildren()-1);clearInterval(k);k=null}}for(var g=f.getChildAt(0),l=g.image,m=16,p=e/m,n=0;n<m;n++){var q=new Quark.Bitmap({id:"maskBitmap"+n,image:l,rect:[0,0,0,0]});q.x=n*p;f.addChild(q)}c=j*b;d=1/c;var k=setInterval(i,1E3/b),r=1;i()};this.mask11=function(f,e,h,j){function i(){for(var b=
0;b<m;b++){var j=b*p,i=e,l=p*r*d;f.getChildById("maskBitmap"+b).setRect([0,j,i,l])}r++;if(r>c||1==a.maskerFull){aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"});for(g.setRect([0,0,e,h]);1<f.getNumChildren();)f.removeChildAt(f.getNumChildren()-1);clearInterval(k);k=null}}for(var g=f.getChildAt(0),l=g.image,m=16,p=h/m,n=0;n<m;n++){var q=new Quark.Bitmap({id:"maskBitmap"+n,image:l,rect:[0,0,0,0]});q.y=n*p;f.addChild(q)}c=j*b;d=1/c;var k=setInterval(i,1E3/b),r=1;i()};this.mask12=
function(f,e,h,j){function i(){for(n=0;n<F;n++)w=k.length,0<w?(E=Math.floor(Math.random()*w),k[E].visible=!0,k.splice(E,1)):n=F;U++;if(U>c||1==a.maskerFull){aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER});for(g.setRect([0,0,e,h]);1<f.getNumChildren();)f.removeChildAt(f.getNumChildren()-1);clearInterval(y);y=null}}for(var g=f.getChildAt(0),l=g.image,m=Math.ceil(e/20),p=Math.ceil(h/20),n=0,q=0,k=[],n=0;20>n;n++)for(q=0;20>q;q++){var r=m*n,t=p*q,x=m,A=p;r<e&&t<
h&&(r>e-m&&(x=e-r),t>h-p&&(A=h-t),x=new Quark.Bitmap({id:"maskBitmap"+n+q,image:l,rect:[r,t,x,A]}),x.x=r,x.y=t,x.visible=!1,f.addChild(x),k.push(x))}c=j*b;d=1/c;var y=setInterval(i,1E3/b),U=1,w=k.length,E,F=Math.round(w/c);1>F&&(F=1);i()};this.mask13=function(f,e,h,j){function i(){l=e/2*(1-k*d);m=h/2*(1-k*d);p=e*k*d;n=h*k*d;g.x=e/2*(1-k*d);g.y=h/2*(1-k*d);g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),
g.x=0,g.y=0,clearInterval(q),q=null}var g=f.getChildAt(0),l=e/2,m=h/2,p=0,n=0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask14=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask15=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask16=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask17=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask18=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask19=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask20=function(a,
b,d,c){this.transition(68,a,b,d,c)};this.mask21=function(f,e,h,j){function i(){l=e*(1-k*d);m=h*(1-k*d);p=e*k*d;n=h*k*d;g.x=e*(1-k*d);g.y=h*(1-k*d);g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.x=0,g.y=0,clearInterval(q),q=null}var g=f.getChildAt(0),l=e,m=h,p=0,n=0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask22=function(f,e,h,j){function i(){l=e*(1-k*d);m=0;p=e*k*d;n=h*k*d;g.x=e*(1-k*
d);g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.x=0,clearInterval(q),q=null}var g=f.getChildAt(0),l=e,m=0,p=0,n=0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask23=function(f,e,h,j){function i(){l=0;m=h*(1-k*d);p=e*k*d;n=h*k*d;g.y=h*(1-k*d);g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.y=
0,clearInterval(q),q=null}var g=f.getChildAt(0),l=0,m=h,p=0,n=0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask24=function(f,e,h,j){function i(){r=e/2*u*d;t=h/2*u*d;g.setRect([q,k,r,t]);x=e/2+e/2*(1-u*d);A=0;y=e/2*u*d;U=h/2*u*d;m.x=e/2+e/2*(1-u*d);m.setRect([x,A,y,U]);w=0;E=h/2+h/2*(1-u*d);F=e/2*u*d;M=h/2*u*d;p.y=h/2+h/2*(1-u*d);p.setRect([w,E,F,M]);N=e/2+e/2*(1-u*d);R=h/2+h/2*(1-u*d);C=e/2*u*d;G=h/2*u*d;n.x=e/2+e/2*(1-u*d);n.y=h/2+h/2*(1-u*d);n.setRect([N,R,C,G]);u++;if(u>c||1==a.maskerFull){aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER});
for(g.setRect([0,0,e,h]);1<f.getNumChildren();)f.removeChildAt(f.getNumChildren()-1);clearInterval(O);O=null}}var g=f.getChildAt(0),l=g.image,m=new Quark.Bitmap({id:"targetBitmap2",image:l,rect:[0,0,0,0]});f.addChild(m);var p=new Quark.Bitmap({id:"targetBitmap3",image:l,rect:[0,0,0,0]});f.addChild(p);var n=new Quark.Bitmap({id:"targetBitmap4",image:l,rect:[0,0,0,0]});f.addChild(n);var q=0,k=0,r=0,t=0,x=e,A=0,y=0,U=0,w=0,E=h,F=0,M=0,N=e,R=h,C=0,G=0;c=j*b;d=1/c;var O=setInterval(i,1E3/b),u=1;i()};this.mask25=
function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask26=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask27=function(f,e,h,j){function i(){for(var b=0;b<m;b++){var j=p*b,i=p;n[b].x>e-p&&(i=e-n[b].x);var l=q[b]+(h-q[b])*y*d*h/(h-q[b]);l<h&&n[b].setRect([j,0,i,l])}y++;if(y>c||1==a.maskerFull){aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER});for(g.setRect([0,0,e,h]);1<f.getNumChildren();)f.removeChildAt(f.getNumChildren()-1);clearInterval(A);A=null}}for(var g=
f.getChildAt(0),l=g.image,m=20,p=Math.ceil(e/m),n=[],q=[],k=0;k<m;k++){q[k]=h/2*Math.random();var r=p*k,t=p,x=q[k];r>e-p&&(t=e-r);t=new Quark.Bitmap({id:"maskBitmap"+k,image:l,rect:[r,0,t,x]});t.x=r;f.addChild(t);n.push(t)}c=j*b;d=1/c;var A=setInterval(i,1E3/b),y=1;i()};this.mask28=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask29=function(f,e,h,j){function i(){g.alpha=m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),g.alpha=
1,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.alpha=0;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask30=function(f,e,h,j){function i(){l=e*(1-k*d);p=e*k*d;g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.x=0,clearInterval(q),q=null}var g=f.getChildAt(0),l=e,m=0,p=0,n=h;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask31=function(f,e,h,j){function i(){g.alpha=
k*d;l=e*(1-k*d);p=e*k*d;g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.x=0,g.alpha=1,clearInterval(q),q=null}var g=f.getChildAt(0);g.alpha=0;var l=e,m=0,p=0,n=h;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask32=function(f,e,h,j){function i(){p=e*k*d;g.setRect([l,m,p,n]);g.x=e*(1-k*d);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,
0,e,h]),g.x=0,clearInterval(q),q=null}var g=f.getChildAt(0);g.x=e;var l=0,m=0,p=0,n=h;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask33=function(f,e,h,j){function i(){g.alpha=k*d;p=e*k*d;g.setRect([l,m,p,n]);g.x=e*(1-k*d);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.x=0,g.alpha=1,clearInterval(q),q=null}var g=f.getChildAt(0);g.x=e;var l=g.alpha=0,m=0,p=0,n=h;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};
this.mask34=function(f,e,h,j){function i(){m=h*(1-k*d);n=h*k*d;g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.y=0,clearInterval(q),q=null}var g=f.getChildAt(0),l=0,m=h,p=e,n=0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask35=function(f,e,h,j){function i(){g.alpha=k*d;m=h*(1-k*d);n=h*k*d;g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),
g.setRect([0,0,e,h]),g.y=0,g.alpha=1,clearInterval(q),q=null}var g=f.getChildAt(0),l=g.alpha=0,m=h,p=e,n=0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask36=function(f,e,h,j){function i(){g.y=h*(1-k*d);n=h*k*d;g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.y=0,clearInterval(q),q=null}var g=f.getChildAt(0);g.y=h;var l=0,m=0,p=e,n=0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask37=
function(f,e,h,j){function i(){g.alpha=k*d;g.y=h*(1-k*d);n=h*k*d;g.setRect([l,m,p,n]);k++;if(k>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:"transitionOver"}),g.setRect([0,0,e,h]),g.y=0,g.alpha=1,clearInterval(q),q=null}var g=f.getChildAt(0);g.alpha=0;g.y=h;var l=0,m=0,p=e,n=0;c=j*b;d=1/c;var q=setInterval(i,1E3/b),k=1;i()};this.mask38=function(f,e,h,j){function i(){g.width=e*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),
g.width=e,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.width=0;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask39=function(f,e,h,j){function i(){g.alpha=m*d;g.width=e*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),g.width=e,g.alpha=1,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.alpha=0;g.width=0;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask40=function(f,e,h,
j){function i(){g.x=e/2*(1-m*d);g.width=e*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),g.width=e,g.x=0,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.width=0;g.x=e/2;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask41=function(f,e,h,j){function i(){g.alpha=m*d;g.x=e/2*(1-m*d);g.width=e*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),
g.width=e,g.x=0,g.alpha=1,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.width=0;g.alpha=0;g.x=e/2;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask42=function(f,e,h,j){function i(){g.x=e*(1-m*d);g.width=e*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),g.width=e,g.x=0,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.width=0;g.x=e;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};
this.mask43=function(f,e,h,j){function i(){g.alpha=m*d;g.x=e*(1-m*d);g.width=e*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),g.width=e,g.x=0,g.alpha=1,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.width=0;g.alpha=0;g.x=e;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask44=function(f,e,h,j){function i(){g.height=h*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),
g.height=h,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.height=0;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask45=function(f,e,h,j){function i(){g.alpha=m*d;g.height=h*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),g.height=h,g.alpha=1,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.height=0;g.alpha=0;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask46=function(f,
e,h,j){function i(){g.y=h/2*(1-m*d);g.height=h*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),g.height=h,g.y=0,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.height=0;g.y=h/2;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask47=function(f,e,h,j){function i(){g.alpha=m*d;g.y=h/2*(1-m*d);g.height=h*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),
g.height=h,g.y=0,g.alpha=1,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.height=0;g.alpha=0;g.y=h/2;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask48=function(f,e,h,j){function i(){g.y=h*(1-m*d);g.height=h*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),g.height=h,g.y=0,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.height=0;g.y=h;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;
i()};this.mask49=function(f,e,h,j){function i(){g.alpha=m*d;g.y=h*(1-m*d);g.height=h*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),g.height=h,g.y=0,g.alpha=1,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.height=0;g.alpha=0;g.y=h;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask50=function(f,e,h,j){function i(){g.x=e/2*(1-m*d);g.y=h/2*(1-m*d);g.width=e*m*d;g.height=h*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),
g.width=e,g.height=h,g.x=0,g.y=0,clearInterval(l),l=null}var g=f.getChildAt(0);g.setRect([0,0,e,h]);g.width=0;g.height=0;g.x=e/2;g.y=h/2;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask51=function(f,e,h,j){function i(){g.alpha=m*d;g.x=e/2*(1-m*d);g.y=h/2*(1-m*d);g.width=e*m*d;g.height=h*m*d;m++;if(m>c||1==a.maskerFull)aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER}),g.width=e,g.height=h,g.x=0,g.y=0,g.alpha=1,clearInterval(l),l=null}var g=f.getChildAt(0);
g.setRect([0,0,e,h]);g.width=0;g.height=0;g.alpha=0;g.x=e/2;g.y=h/2;c=j*b;d=1/c;var l=setInterval(i,1E3/b),m=1;i()};this.mask52=function(a,b,d){a.getChildAt(0).setRect([0,0,b,d]);aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER})};this.mask53=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask54=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask55=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask56=function(a,b,d,c){this.transition(68,a,b,d,c)};
this.mask57=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask58=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask59=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask60=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask61=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask62=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask63=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask64=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask65=function(a,b,d,c){this.transition(68,
a,b,d,c)};this.mask66=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask67=function(a,b,d,c){this.transition(68,a,b,d,c)};this.mask68=function(f,e,h,j){function i(){for(n=0;n<u;n++)k[n].width=y[n]*O*d,k[n].height=U[n]*O*d,k[n].x=x[n]+(r[n]-x[n])*O*d,k[n].y=A[n]+(t[n]-A[n])*O*d;O++;if(O>c||1==a.maskerFull){aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.TRANSITION_OVER});for(g.setRect([0,0,e,h]);1<f.getNumChildren();)f.removeChildAt(f.getNumChildren()-1);clearInterval(G);
G=null}}for(var g=f.getChildAt(0),l=g.image,m=Math.ceil(e/12),p=Math.ceil(h/12),n=0,q=0,k=[],r=[],t=[],x=[],A=[],y=[],U=[],n=0;12>n;n++)for(q=0;12>q;q++){var w=m*n,E=p*q,F=m,M=p,N=Math.random()*(e-m),R=Math.random()*(h-p);if(w<e&&E<h){w>e-m&&(F=e-w);E>h-p&&(M=h-E);var C=new Quark.Bitmap({id:"maskBitmap"+n+q,image:l,rect:[w,E,F,M]});C.x=N;C.y=R;C.width=0;C.height=0;f.addChild(C);k.push(C);r.push(w);t.push(E);y.push(F);U.push(M);x.push(N);A.push(R)}}c=j*b;d=1/c;var G=setInterval(i,1E3/b),O=1,u=k.length;
i()}}})();
(function(){aJSs.JsXmlLoad=function(b){var a=this;a.copyright="Anvsoft";a.movieWidth=0;a.movieHeight=0;a.startAutoPlay="";a.continuum="";a.clickToAutoPlay="";a.randomPlayingPhotos="";a.enableURL="";a.movieBackgroundColor="";a.loadStyle="";a.anvsoftMenu="";a.frameRate=0;a.globalTitleXml="";a.musicPath="";a.musicStream="";a.musicLoop="";a.musicAutoPlay="";a.topPadding=0;a.bottomPadding=0;a.leftPadding=0;a.rightPadding=0;a.globalDescriptionXml="";a.videoAutoPlay="";a.bufferTime="";a.videoControls="";
a.thumbnailBasicXml="";a.thumbnailArray=[];a.photoArray=[];a.photoUrlArray=[];a.URLTarget=[];a.videoArray=[];a.transitionArray=[];a.photoTimeArray=[];a.transitionTimeArray=[];a.defineTransitionArray=[];a.photoTitleArray=[];a.descriptionText=[];var c=function(b){b=b.documentElement;a.copyright=b.getAttribute("copyright");var d=b.getElementsByTagName("global")[0],c=d.getElementsByTagName("basic_property")[0];a.movieWidth=c.getAttribute("movieWidth");a.movieHeight=c.getAttribute("movieHeight");a.startAutoPlay=
c.getAttribute("startAutoPlay");a.continuum=c.getAttribute("continuum");a.clickToAutoPlay=c.getAttribute("clickToAutoPlay");a.randomPlayingPhotos=c.getAttribute("randomPlayingPhotos");a.enableURL=c.getAttribute("enableURL");a.movieBackgroundColor=c.getAttribute("backgroundColor").replace(/0x/g,"#");a.loadStyle=c.getAttribute("loadStyle");a.anvsoftMenu=c.getAttribute("anvsoftMenu");a.frameRate=c.getAttribute("frameRate");c=c.getAttribute("transitionArray");a.defineTransitionArray=""==c?null:c.split(",");
a.globalTitleXml=d.getElementsByTagName("title_property")[0];c=d.getElementsByTagName("music_property")[0];a.musicPath=c.getAttribute("path");a.musicStream=c.getAttribute("stream");a.musicLoop=c.getAttribute("loop");a.musicAutoPlay=c.getAttribute("autoPlay");c=d.getElementsByTagName("photo_property")[0];a.topPadding=Number(c.getAttribute("topPadding"));a.bottomPadding=Number(c.getAttribute("bottomPadding"));a.leftPadding=Number(c.getAttribute("leftPadding"));a.rightPadding=Number(c.getAttribute("rightPadding"));
a.globalDescriptionXml=d.getElementsByTagName("description_property")[0];d=d.getElementsByTagName("video_property")[0];a.videoAutoPlay=d.getAttribute("autoPlay");a.bufferTime=Number(d.getAttribute("bufferTime"));a.videoControls=d.getAttribute("controls");d=b.getElementsByTagName("thumbnail")[0];void 0!=d&&(a.thumbnailBasicXml=d.getElementsByTagName("basic_property")[0]);b=b.getElementsByTagName("album")[0].getElementsByTagName("slide");d=b.length;for(c=0;c<d;c++){a.thumbnailArray[c]=b[c].getAttribute("jpegURL");
a.photoArray[c]=b[c].getAttribute("d_URL");a.photoUrlArray[c]=b[c].getAttribute("url");a.URLTarget[c]=b[c].getAttribute("URLTarget");a.videoArray[c]=b[c].getAttribute("v_URL");a.transitionArray[c]=b[c].getAttribute("transition");a.photoTimeArray[c]=b[c].getAttribute("phototime");a.transitionTimeArray[c]=b[c].getAttribute("transitiontime");a.photoTitleArray[c]=b[c].getAttribute("title");var e=b[c].childNodes[0];a.descriptionText[c]=void 0!=e?e.nodeValue:""}};try{var d=new ActiveXObject("Microsoft.XMLDOM")}catch(f){try{d=
document.implementation.createDocument("","",null)}catch(e){alert(e.message)}}try{d.async=!1,d.load(b),c(d)}catch(h){try{var j=new window.XMLHttpRequest;j.open("GET",b,!1);j.send(null);d=j.responseXML;c(d)}catch(i){d=(new DOMParser).parseFromString(window.anvsoftJavaScriptSlideshowData,"text/xml"),c(d)}}}})();
(function(){aJSs.JsCompatibleTheme=function(b,a,c){function d(){q--;0>=q&&(clearInterval(r),k++,k>n-1&&(k=0),x.src=c+e[k])}var f=b.movieBackgroundColor,e=b.photoArray,h=b.photoUrlArray,j=b.photoTimeArray,i=b.transitionTimeArray,g=b.URLTarget,l=b.topPadding,m=b.bottomPadding,p=b.leftPadding,b=b.rightPadding,n=e.length,q=0,k=0,r=null,t=document.getElementById(a);t.style.backgroundColor=f;var a=t.offsetWidth,f=t.offsetHeight,p=a-p-b,l=f-l-m,m=Math.round((a-p)/2),b=Math.round((f-l)/2),x=new Image;t.appendChild(x);
x.style.position="absolute";x.style.width=p+"px";x.style.height=l+"px";x.style.left=m+"px";x.style.top=b+"px";x.src=c+e[k];x.onload=function(){q=parseInt(i[k])+parseInt(j[k]);r=setInterval(d,1E3)};x.onclick=function(){var a;switch(g[k]){case "0":a="_blank";break;case "1":a="_parent";break;case "2":a="_self";break;case "3":a="_top";break;default:a="_blank"}window.open(h[k],a)};var A=document.createElement("div");t.appendChild(A);A.style.position="absolute";A.style.width="250px";A.style.padding="8px";
A.style.backgroundColor="#333";A.style.color="#FFF";A.style.textAlign="left";A.style.font="normal normal 12px/16px verdana,tahoma,arial,sans-serif";A.innerHTML="The browser you are using does not support HTML5. Now you are using the simple compatible mode. To get better user experience, please use HTML5 supported browser.";A.style.left=Math.round((a-A.offsetWidth)/2)+"px";A.style.top=Math.round((f-A.offsetHeight)/2)+"px";var y=setTimeout(function(){clearTimeout(y);y=null;t.removeChild(A)},1E4)}})();
(function(){aJSs.JsBackground=function(b,a){var c=b.movieBackgroundColor,d=new Quark.DisplayObjectContainer({id:"backgroundBox"});d.autoSize=!0;a.addChild(d);if(""!=c){var f=Quark.Bitmap,e=a.width,h=a.height,j=document.createElement("canvas");j.width=e;j.height=h;var i=j.getContext("2d");i.fillStyle=c;i.rect(0,0,e,h);i.fill();c=new Image;c.src=j.toDataURL("image/png");c.width=e;c.height=h;f=new f({id:"background",image:c});f.autoSize=!0;d.addChild(f)}}})();
(function(){aJSs.JsPhoto=function(b,a,c){function d(){aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.VIDEO_CLEAR});if(""!=y){e();var a=new Image;a.src=c+y;a=new Quark.MovieClip({image:a,id:"preloader",interval:100});a.addFrame([{rect:[0,0,25,25]},{rect:[25,0,25,25]},{rect:[50,0,25,25]},{rect:[75,0,25,25]},{rect:[100,0,25,25]},{rect:[125,0,25,25]}]);a.x=t+(M-a.width)/2;a.y=k+(N-a.height)/2;T.addChild(a)}O=G=0;V&&V.removeAllChildren();D.swapChildren(Y,Z);D.getChildIndex(Y)>D.getChildIndex(Z)?
(X=Y,V=Z):(X=Z,V=Y);var b=new Image;b.onload=function(){e();G=1;b.width=K;b.height=B;var a=new Quark.Bitmap({id:"targetBitmap",image:b,rect:[0,0,0.0010,0.0010]});a.useHandCursor="true"==g&&""!=i[s]?!0:!1;X.addChild(a);J=0==p[s]?null==n?Math.floor(Math.random()*L.transTotal)+1:n[Math.floor(Math.random()*n.length)]:p[s];L.transition(J,X,K,B,q[s]);a.onEvent=function(a){if("mousedown"==a.type||"touchend"==a.type){if("true"==g&&""!=i[s]){switch(l[s]){case "0":a="_blank";break;case "1":a="_parent";break;
case "2":a="_self";break;case "3":a="_top";break;default:a="_blank"}window.open(i[s],a)}}else"mousemove"==a.type||"touchmove"==a.type?aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.PHOTO_MOUSE_OVER}):("mouseout"==a.type||"touchout"==a.type)&&aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.PHOTO_MOUSE_OUT})};aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.PHOTO_LOAD_COMPLETE,index:s})};b.src=c+j[s];aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.PLAY_CURRENT,
index:s});s>=P-1&&"false"==w&&"false"==A&&R.Pause()}function f(){z--;try{Quark.getDOM("debugInfo").value=z}catch(a){}if(0>=z||1==u)clearInterval(I),I=null,0==u?"true"==A?s=Math.floor(Math.random()*P):s<P-1?s++:s=0:u=0,d()}function e(){if(""!=y){var a=T.getChildById("preloader");null!=a&&T.removeChild(a)}}var h=b.frameRate,j=b.photoArray,i=b.photoUrlArray,g=b.enableURL,l=b.URLTarget,m=b.photoTimeArray,p=b.transitionArray,n=b.defineTransitionArray,q=b.transitionTimeArray,k=b.topPadding,r=b.bottomPadding,
t=b.leftPadding,x=b.rightPadding,A=b.randomPlayingPhotos,y=b.loadStyle,U=b.startAutoPlay,w=b.continuum,E=b.videoAutoPlay,F=b.videoArray,M=a.width-t-x,N=a.height-k-r,R=this,C=0,G=1,O=1,u=0,J=0,z=0,s=0,I=null,P=j.length;aJSs.CommandDispatcher.getInstance().addEventListener(aJSs.Events.TRANSITION_OVER,function(){O=1;if(1==C||1==u)z=m[s]*h,I=setInterval(f,1E3/h);""!=F[s]&&void 0!=F[s]&&0==u&&("true"==E&&(clearInterval(I),I=null),aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.PLAY_VIDEO,
index:s,width:M,height:N}))});aJSs.CommandDispatcher.getInstance().addEventListener(aJSs.Events.PLAY_NEXT,function(){R.Play()});aJSs.CommandDispatcher.getInstance().addEventListener(aJSs.Events.VIDEO_START_PLAY,function(){R.Pause()});var L=new aJSs.MaskEffect(h),T=new Quark.DisplayObjectContainer({id:"container"});T.autoSize=!0;a.addChild(T);var K=a.width-t-x,B=a.height-k-r,b=t,a=k,r=Quark.Bitmap,x=K,W=B,S="#DDD",H=document.createElement("canvas");H.width=x;H.height=W;var v=H.getContext("2d");v.fillStyle=
S;v.rect(0,0,x,W);v.fill();S=new Image;S.src=H.toDataURL("image/png");S.width=x;S.height=W;r=new r({id:"photoBoxBg",image:S});r.autoSize=!0;r.x=b;r.y=a;T.addChild(r);var D=new Quark.DisplayObjectContainer({id:"photoBox",x:b,y:a,width:K,height:B});D.autoSize=!0;T.addChild(D);var V,X,Y=new Quark.DisplayObjectContainer({id:"aPhoto"}),Z=new Quark.DisplayObjectContainer({id:"bPhoto"});D.addChild(Y);D.addChild(Z);this.Play=function(){C=1;1==G&&1==O?(clearInterval(I),I=null,s<P-1?s++:s=0,d()):1==G&&0==O?
(u=1,s<P-1?s++:s=0,L.maskerFull=1):(s<P-1?s++:s=0,u=1)};this.Pause=function(){C=0;null!=I&&(clearInterval(I),I=null)};this.Previous=function(a){C=a;0<s?s--:s=P-1;1==G&&1==O?(clearInterval(I),I=null,d()):1==G&&0==O?(u=1,L.maskerFull=1):u=1};this.Next=function(a){C=a;s<P-1?s++:s=0;1==G&&1==O?(clearInterval(I),I=null,d()):1==G&&0==O?(u=1,L.maskerFull=1):u=1};this.Show=function(a,b){C=b;1==G&&1==O?(clearInterval(I),I=null,s=a,d()):1==G&&0==O?(u=1,s=a,L.maskerFull=1):(s=a,u=1)};"true"==U?this.Show(0,1):
this.Show(0,0)}})();
(function(){aJSs.JsMediaConsole=function(b,a,c,d){function f(){void 0!=r&&(b.removeChild(r),void 0!=k&&"videoCallPause"==t&&(k.Play(),t=""),r=void 0,e())}function e(){var a=document.getElementById("videoLoadText");a&&b.removeChild(a)}var h=a.topPadding,j=a.leftPadding,c=a.musicPath,i=a.musicAutoPlay,g=a.musicLoop,l=a.musicStream,m=a.videoAutoPlay,p=a.bufferTime,n=a.videoArray,q=a.videoControls;if(""!=c)var k=new aJSs.Music(d+c,l,i,g);var r,t="";aJSs.CommandDispatcher.getInstance().addEventListener(aJSs.Events.PLAY_VIDEO,function(a){var c=
a.index,e=a.width,a=a.height;void 0!=k&&k.Playing()&&(k.Pause(),t="videoCallPause");r=new aJSs.Video(d+n[c],m,p,q,e,a);r.style.backgroundColor="#000";r.style.position="absolute";r.style.top=h+"px";r.style.left=j+"px";b.appendChild(r);c=document.getElementById("videoLoadText");null==c&&(c=document.createElement("div"),c.id="videoLoadText",c.style.position="absolute",c.style.top=h+5+"px",c.style.left=j+5+"px",c.style.font="normal normal 11px/13px verdana,tahoma,arial,sans-serif",c.style.color="#FFF",
c.textContent="Waiting...",b.appendChild(c))});aJSs.CommandDispatcher.getInstance().addEventListener(aJSs.Events.VIDEO_PLAY_ENDED,function(){f();aJSs.CommandDispatcher.getInstance().dispatchEvent({type:aJSs.Events.PLAY_NEXT})});aJSs.CommandDispatcher.getInstance().addEventListener(aJSs.Events.VIDEO_CLEAR,function(){f()});aJSs.CommandDispatcher.getInstance().addEventListener(aJSs.Events.VIDEO_START_PLAY,function(){e()});this.MusicPlay=function(){k.Play()};this.MusicPause=function(){k.Pause()}}})();
(function(){aJSs.JsMenu=function(b,a){var c=b.topPadding,d=b.leftPadding,f=b.copyright;if(null==b.anvsoftMenu||"anvsoftPFMTheme"!=f&&"anvsoftUSSTheme"!=f&&"anvsoftHSMTheme"!=f){var e,h;switch(f){case "anvsoftPFMTheme":h="Powered by photo-flash-maker.com";e=186;break;case "anvsoftUSSTheme":h="Powered by ultraslideshow.com";e=168;break;case "anvsoftHSMTheme":h="guyueshuiming";e=100;break;case "anvsoftSWWTheme":h="Powered by slidewow.com";e=142;break;default:h="Powered by anvsoft.com",
e=136}var j=new Quark.DisplayObjectContainer({id:"menudBox"});j.autoSize=!0;j.x=d;j.y=c;/*a.addChild(j);*comment by wzj*/var c=Quark.Bitmap,d=e,i="#000",g=document.createElement("canvas");g.width=d;g.height=20;var l=g.getContext("2d");l.fillStyle=i;l.rect(0,0,d,20);l.fill();i=new Image;i.src=g.toDataURL("image/png");i.width=d;i.height=20;c=new c({id:"copyrightBg",image:i});c.autoSize=!0;c.alpha=0.3;j.addChild(c);c=Quark.Bitmap;d=e;i="#FFF";g=h;h=document.createElement("canvas");h.width=d;h.height=20;d=h.getContext("2d");
d.font="11px arial, sans-serif";d.textAlign="start";d.textBaseline="middle";d.fillStyle=i;d.fillText(g,0,10);d=g=d.measureText(g).width;i=new Image;i.src=h.toDataURL("image/png");i.width=d;i.height=20;h=new c({id:"copyrightText",image:i});h.useHandCursor=!0;h.autoSize=!0;h.x=Math.round((e-g)/2);j.addChild(h);h.onEvent=function(a){if("mousedown"==a.type||"touchend"==a.type)switch(f){case "anvsoftPFMTheme":window.open("http://www.photo-flash-maker.com/","_self");break;case "anvsoftUSSTheme":window.open("http://www.ultraslideshow.com/",
"_self");break;case "anvsoftHSMTheme":window.open("http://wzjwzj.github.io/","_self");break;case "anvsoftSWWTheme":window.open("http://www.slidewow.com/","_self");break;default:window.open("http://www.anvsoft.com/","_self")}}}}})();
(function(){aJSs.JsInterface=function(b,a,c,d,f){this.globalPath=f;this.container=b;this.commandDispatcher=aJSs.CommandDispatcher.getInstance();this.copyright=a.copyright;this.movieWidth=a.movieWidth;this.movieHeight=a.movieHeight;this.startAutoPlay=a.startAutoPlay;this.continuum=a.continuum;this.clickToAutoPlay=a.clickToAutoPlay;this.randomPlayingPhotos=a.randomPlayingPhotos;this.enableURL=a.enableURL;this.movieBackgroundColor=a.movieBackgroundColor;this.loadStyle=a.loadStyle;this.anvsoftMenu=a.anvsoftMenu;
this.frameRate=a.frameRate;this.globalTitleXml=a.globalTitleXml;this.musicPath=a.musicPath;this.musicStream=a.musicStream;this.musicLoop=a.musicLoop;this.musicAutoPlay=a.musicAutoPlay;this.topPadding=a.topPadding;this.bottomPadding=a.bottomPadding;this.leftPadding=a.leftPadding;this.rightPadding=a.rightPadding;this.globalDescriptionXml=a.globalDescriptionXml;this.videoAutoPlay=a.videoAutoPlay;this.bufferTime=a.bufferTime;this.videoControls=a.videoControls;this.thumbnailBasicXml=a.thumbnailBasicXml;
this.thumbnailArray=a.thumbnailArray;this.photoArray=a.photoArray;this.photoUrlArray=a.photoUrlArray;this.URLTarget=a.URLTarget;this.videoArray=a.videoArray;this.transitionArray=a.transitionArray;this.photoTimeArray=a.photoTimeArray;this.transitionTimeArray=a.transitionTimeArray;this.defineTransitionArray=a.defineTransitionArray;this.photoTitleArray=a.photoTitleArray;this.descriptionText=a.descriptionText;this.Play=function(){c.Play()};this.Pause=function(){c.Pause()};this.Previous=function(){c.Previous()};
this.Next=function(){c.Next()};this.Show=function(a,b){c.Show(a,b)};this.MusicPlay=function(){d.MusicPlay()};this.MusicPause=function(){d.MusicPause()}}})();
(function(b){var a=aJSs.getParameters.parameters().xml_path,c=aJSs.getParameters.parameters().fs_path,d,f;void 0==a?void 0==c?(d="slides.xml",f=""):(d=c+"/slides.xml",f=c+"/"):(d=a,f=a.substr(0,a.lastIndexOf("/")+1));anvsoftJavaScriptSlideshow.init=function(a){var c,j;if(b.document.createElement("canvas").getContext){var a=Quark.getDOM(a),i=Quark.supportTouch?["touchstart","touchmove","touchend","touchout"]:["mousedown","mousemove","mouseup","mouseout"],g=Quark.getUrlParams();void 0==g.mode&&(g.mode=
1);var l=a.clientWidth||a.offsetWidth,m=a.clientHeight||a.offsetHeight;1==g.mode?(c=Quark.createDOM("canvas",{width:l,height:m}),a.appendChild(c),j=new Quark.CanvasContext({canvas:c})):j=new Quark.DOMContext({canvas:a});c=new Quark.Stage({width:l,height:m,context:j});(new Q.EventManager).registerStage(c,i);j=new aJSs.JsXmlLoad(d);i=new aJSs.JsPhoto(j,c,f);g=new aJSs.JsMediaConsole(a,j,c,f);new aJSs.JsMenu(j,c);l=new Q.Timer(1E3/j.frameRate);l.addListener(c);l.start();j=new aJSs.JsInterface(a,j,i,
g,f);new aJSsTemplate.Main(j)}else c=new aJSs.JsXmlLoad(d),new aJSs.JsCompatibleTheme(c,a,f)}})(window);
